### ISSUE TITLE
[Feature Request] Pokemon Level Column and Trainer Stats Window

### ISSUE THREAD

**Issue by ShawnHardwick** [Wolfsblvt/BlossomsPokemonGoManager#10]
Some initial impressions that I got from using this Pokemon Manager. You may already have some of these on your to-do list:
- Display Trainer stats as a status field or its own box instead of a window (mainly for stardust)
- Display Pokemon level as a field, upgrading without knowing the level is nearly useless although the required stardust field is helpful.

**Comment by weblue** [comment]
I added stardust part of the window title. I'm gonna add pokemon level now

**Comment by weblue** [comment]
Added levels. Will soon reorder the columns

**Comment by weblue** [comment]
Done
