### ISSUE TITLE
[Suggestion] Sorting by catch date

### ISSUE THREAD

**Issue by Treeston** [Wolfsblvt/BlossomsPokemonGoManager#101]
As the title says. Would make processing recent catches after you RTB far simpler.

**Comment by Ljaysoft** [comment]
Already included in the next build.

**Comment by Wolfsblvt** [comment]
Yep, included in #54.

**Comment by Treeston** [comment]
Awesome! Build the dev branch for myself now, so much nicer. Thanks for the help.
