### ISSUE TITLE
Anytime Failed login

### ISSUE THREAD

**Issue by thomashaentjens** [Wolfsblvt/BlossomsPokemonGoManager#103]
Hi,

First great job and thank you for your work.

I do have an issue, each time i try to login i have the same problem, "Unfortunately, your login has failed. Press OK to try it again.".

I doubled check Id and Password in the game and everything work flawlessly. I tried to remove the config file and to add my login and password manually ( i may have done wrongly on this one ) but still not working.

Again great work as those infos are obviously hidden for no understandable reasons.

Sorry about my grammar ( I'm french actually )

Cheers.

**Comment by Ljaysoft** [comment]
See #102
