### ISSUE TITLE
nothing happens after Login

### ISSUE THREAD

**Issue by RRTogunov** [Wolfsblvt/BlossomsPokemonGoManager#106]
version 0.1.0 and 0.1.1 both worked until a couple days ago. after inputting correct login information, the login window closes, but the main application does not open a window. However, even though nothing is open a javaw.exe process is shown as running in Taskmanager.  No other symptoms.

**Comment by Wolfsblvt** [comment]
Try deleting the config.json in the same folder where the jar file is.

**Comment by RRTogunov** [comment]
works now. Thanks
