### ISSUE TITLE
Rounding Up Half-Levels

### ISSUE THREAD

**Issue by Lacero** [Wolfsblvt/BlossomsPokemonGoManager#109]
Pokemon can be at half levels. My level 16.5 Starmie shows up incorrectly as 17 in the UI. Need to change data type to a non-integer in PokemonTab:

ArrayList<Integer>  levelCol = new ArrayList<>();//4

**Comment by Ljaysoft** [comment]
edit: was not fixed, fixing atm
edit2:its indeed fixed on the develop branch

**Comment by Wolfsblvt** [comment]
Sure, I have fixed that already :P
