### ISSUE TITLE
[Suggestion] Add capability to append IV to names of selected Pokemon

### ISSUE THREAD

**Issue by Ulua** [Wolfsblvt/BlossomsPokemonGoManager#114]
Ive been adding the IV% to the end of the names of the Pokemon in game. This is tremendously useful when a player has multiple Pokemon of the same type and wants to be able to consider IV when selecting for gym fight order, etc.

Would have to handle length of name limit restriction in some manner.

**Comment by JTorch** [comment]
I agree with this, but I would add that the IV% should be appended to the beginning, not the end of the nickname. I've been adding it at the beginning so that sorting by name in-game actually sorts by IV. (There's no need to actually sort by name when sorting by Pokedex number works just as well.)

**Comment by Wolfsblvt** [comment]
Oh guys, you are so sweet! :D 
It's not your fault, you can't know that, we are heavily working and need more time for the next release, but that feature is already finished, and even more advanced.

Read up issue #47 for more information on how it will work.
