### ISSUE TITLE
"Check for new version" - Feature

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#116]
The app should check on startup if there is a new version available of this application.

For that, we need a version number set somewhere in the web, for example inside the git project, that we update for every new release.
If there is a new version, user should be asked if he wants to download it and then get redirected to the releases page.

**Comment by thomashaentjens** [comment]
Great idea, it would be even better to download and install it for them as the soft is running in java and we do have a config file I think that a simple script would be doing it something like : 
on opening : 

```
new version ?
yes : 
- license change ?
- yes : 
-- user agreement ( license, download and install ) ?
-- yes : 
--- download new .jar file
--- close curent version
--- replace .jar file
--- start app
-- no : 
--- close update
- no : 
-- user agreement ( download and install ) ?
-- yes : 
--- download new .jar file
--- close curent version
--- replace .jar file
--- start app
-- no : 
--- close update
no : 
- keep running
```

what do you think ?

**Comment by Wolfsblvt** [comment]
Would be possible, yes. I will dive deeper into it later. First I guess we should make the next release.
