### ISSUE TITLE
Can we have a Sort by recent

### ISSUE THREAD

**Issue by nibewiahn** [Wolfsblvt/BlossomsPokemonGoManager#118]
It would be nice to check the recently caught pokemons!!

**Comment by OSwoboda** [comment]
Already implemented in master, it's coming with next release.

**Comment by Wolfsblvt** [comment]
As said above, is already implemented in #54 and will ship with the next release (:

**Comment by nibewiahn** [comment]
I read the new releases i couldnt find it sry!

**Comment by Wolfsblvt** [comment]
Yeah, no problem. It just takes some time for the next release, so I understand that people don't see what's finished for the next release but not already released.

For that we are here. Better more issues that we close than missing some that we haven't found.

**Comment by nibewiahn** [comment]
Understood, do we already have double sort, lets say i want to my pokemons by ascending ID and descending IV % can we like "Double Sort"?

**Comment by weblue** [comment]
yeah, just sort by IV% first then ID

**Comment by Wolfsblvt** [comment]
Multi-sort feature will be implemented fully in the future.
For now go for the solution weblue suggests. Just order backwards. Least valued ordering first, then the next, and the primary ordering last. The table keeps the sort before with a new sort when the values are identically.

**Comment by nibewiahn** [comment]
Yeah it works ty very much!!I am only using this tools to see my IV, tired of those websites that keeps getting shut down! Plus yours i practical clean and fast...Do you think i ill get my acc flag if i only use to get my acc flagged?

Source Unknown6 TEAM: 
05/08/2016 - 18:43 GMT+1 : Just another quick update, we have discovered that users utilizing MITM techniques may be getting flagged by Niantic servers. Please note read-only MITM is not affected by this flagging. We've confirmed this to the best of our joint abilities, if we discover anything else, we'll be sure to update, however, this should be not a cause for panic at this stage.

**Comment by Wolfsblvt** [comment]
It is possible that you get flagged for using this tool, yes.

**Comment by weblue** [comment]
although MITM will get flagged, this application isn't MITM and doesn't foreseeably need any of the Unknowns

**Comment by weblue** [comment]
I was working on researching the humanization to make sure the manager looks as close to the app as possible and so far, we look pretty clean and I don't see any reason for us to get you flagged.
As always though, use at your own risk

**Comment by nibewiahn** [comment]
But what about when u transfer pokemons or evolve them? Ins't it too fast???  I noticed that the transfers now ignore the fav pokemons, will you guys add the ability to set ur pokemon favorite tru the manager?

**Comment by nibewiahn** [comment]
I was trying to find a donation link is there any???

**Comment by Wolfsblvt** [comment]
Delay for bulk operations will Be added. Favorite ignore for transfer too. Setting favorites as well :P 

For donations, there is none right now. We are talking internally about it.

**Comment by nibewiahn** [comment]
OK let me now!

**Comment by nibewiahn** [comment]
I noticed that whenever u refresh Pokemon it undo all columns u changed and the sort options are you guys going to change it next release or should i open a new request?

**Comment by Wolfsblvt** [comment]
We will do. Issue for that: #65.
