### ISSUE TITLE
Strange transfer behavior

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#119]
As you can see in the output: I got 0 candies and after that 2, multiple times.

> [08/09 09:14:46]: Doing Transfer 1 of 8
> [08/09 09:14:47]: Transferring Taubsi, Result: Success!
> [08/09 09:14:47]: Stat changes: (Candies : 438[+1])
> [08/09 09:14:47]: Doing Transfer 2 of 8
> [08/09 09:14:48]: Transferring Taubsi, Result: Success!
> [08/09 09:14:48]: Stat changes: (Candies : 438[+0])
> [08/09 09:14:48]: Doing Transfer 3 of 8
> [08/09 09:14:49]: Transferring Taubsi, Result: Success!
> [08/09 09:14:49]: Stat changes: (Candies : 440[+2])
> [08/09 09:14:49]: Doing Transfer 4 of 8
> [08/09 09:14:50]: Transferring Taubsi, Result: Success!
> [08/09 09:14:50]: Stat changes: (Candies : 440[+0])
> [08/09 09:14:50]: Doing Transfer 5 of 8
> [08/09 09:14:51]: Transferring Taubsi, Result: Success!
> [08/09 09:14:51]: Stat changes: (Candies : 442[+2])
> [08/09 09:14:51]: Doing Transfer 6 of 8
> [08/09 09:14:52]: Transferring Taubsi, Result: Success!
> [08/09 09:14:52]: Stat changes: (Candies : 442[+0])
> [08/09 09:14:52]: Doing Transfer 7 of 8
> [08/09 09:14:54]: Transferring Taubsi, Result: Success!
> [08/09 09:14:54]: Stat changes: (Candies : 444[+2])
> [08/09 09:14:54]: Doing Transfer 8 of 8
> [08/09 09:14:55]: Transferring Taubsi, Result: Success!
> [08/09 09:14:55]: Stat changes: (Candies : 444[+0])

I'm on current master, not release version.

Edit: Only happened once. I transfered a bunch of other mon and all went ok.

**Comment by Wolfsblvt** [comment]
Can be that the inventory is not refreshed properly.
I will look into it later.

**Comment by weblue** [comment]
Possibly not getting a server response soon enough?

**Comment by Wolfsblvt** [comment]
The refresh of inventory shouldn't be asynchronuous though. So it should actually wait for data - or for an exception.

**Comment by Wolfsblvt** [comment]
@OSwoboda Can you replicate that error again?
I have tried it locally and the error never occured to me. Maybe it was just a one-time-problem?

**Comment by Wolfsblvt** [comment]
With the newest delay added, I don't think it will occur anymore. Closed here.

If it does occur again, reopen please.
