### ISSUE TITLE
Translate Pokémon

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#12]
I'm from Germany and need to look up the names for the Pokémon often. There is no need for other things to translate, but the names of the Pokémon.

**Comment by SuigetsuSake** [comment]
I'm from france and i agree that translations would be nice, i would gladly do the translation for french. Even though it is not a top priority feature, it would be easier to implement now than when the app will be way bigger

**Comment by wullxz** [comment]
I'm working on it right now...

**Comment by ghost** [comment]
I think that would be fantastic. We'd have to implement some sort of localization system, but i'm sure it can be done reasonably!

**Comment by wullxz** [comment]
It's not much of a change for the pokemon names only, because it's in the PokeGOAPI.
My issue is, that I'm not a GUI person and I want it to be saved to config.json so the user doesn't have to re-set his language all the time.

**Comment by ghost** [comment]
I'm not sure what you mean, are we able to set the name of a pokemon through the API, or am i misunderstanding?

**Comment by OSwoboda** [comment]
Thanks a lot! And it was so fast implemented :D

**Comment by Wolfsblvt** [comment]
Was resolved with #35 already. Closed here.
