### ISSUE TITLE
Please add some description [Enhancement]

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#122]
Please add attack type like 

> Psybeam (5.19dps, Water)

Show asterisk near favorite pokemons and skip they when try to Transfer (no API operation required).

Show weight/size and XS/XL markers.

Show catching time and GPS place.

**Comment by Wolfsblvt** [comment]
Attack type would be cool, yes.

Favorite handling will be done with #58.

Catch time is already done and will ship with the next version, done in #54.

Is GPS and weight/size columns really needed? Do they hold any relevant value?

**Comment by QuAzI** [comment]
Some people told me that pokemon speed depends on weight/size but possible it is mistake.

GPS is just for know where pokemon spawned and check this place next time.

**Comment by Wolfsblvt** [comment]
We can just display GPS as coordinates, that wouldn't help much I would say.
And weight/size has no influence in the game at the moment, other than those few medals you can earn for Rattatas and stuff.

So I would say those columns would really just overblow the TableModel, and are not needed.
