### ISSUE TITLE
Improved ordering [enhancement]

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#127]
Check box required for grouping by type (weedle, kakuna and beedrill must be near) and order by evolution level (Weedle first, than kakuna, than beedrill) as first ordering rule. And than order by IV, CP, HP or other defined by user as second order. 
Now records can be ordered only by Id or Species or IV or CP and this informations doesn't play together.

Also ordering not saved now. After any operation it resets to order by id.

**Comment by Wolfsblvt** [comment]
In #65 Multi-sorting will be added, and the not saving will be fixed.
You should be order by all columns then too.
