### ISSUE TITLE
Advanced evolution helper [enhancement]

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#128]
I evolve pokemons only with enabled "Lucky egg" and have *2 for expirience and *2 for new types.
There are two ways to have best evolution way:
1) Fast user evolution - small pokemons (with lower candy price for evolution) must be evolved as many as user can evolve.
2) Fast pokemons army evolution - all pokemons with higher level and max IV/CP must be evolved first. Than small pokemons must be evolved while candies exist.
- if new pokemon (not opened in pokedex) can be opened - this must be opened first (user will have 2000 XP and new powerfull pokemon)

Software can't evolve pokemons under lucky egg now and I mark pokemons for evolve as "Favorite", order it by "Favorite" in game, enable "Lucky egg" and than evolve while time not ends or candies not ends.
Can you create button with wizard for automark pokemons as "Favorite" before evolve and button "clear favorites" after evolve?

Also improved ordering #127 and asterisk near favorite #122 need for me for help properly evolve pokemons.

**Comment by Wolfsblvt** [comment]
Yeah, ordering will be reworked and Favorites will be added.
For viewing good IVs and high CPs, or even where you can't evolve from candies or when it doesn't have a higher evolution, there will be color-codes added soon, I would say. See #123 for that.

For selecting and automating the Lucky Egg phase... I am not sure if that's a good idea. Would be very difficutla to implement and I guess the user can decide better what he wants, if it's displayed better than it is at the moment.

Do you think the improved ordering, color-coded cells and favorite system would be enough to make the evolving phase easy for you?

**Comment by weblue** [comment]
even adding the unfavorite after evolve thing seems like a really niche edge case

**Comment by QuAzI** [comment]
The first message is a little corrected.

I have two problems:
1) Too many time spend for choose best pokemons for evolve through game menu - improved sorting and highlighting helps to decrease time and wizard for automarkup also will help save time.
2) With enabled "Lucky egg" too many time spend for find pokemon - ordering by "Favorite" in game solve this. But after evolving has no sense to stay "Favorite".

I manually recheck the list and evolve pokemons in game. Possible it decrease chance to be banned. Your software used by me only for 
- check IV
- transfer pokemons with low IV to lab 
- determine which pokemons must be evolved (high IV and have candies)

**Comment by QuAzI** [comment]
> For selecting and automating the Lucky Egg phase.

It  is not automating the Lucky Egg in direct case. It is just "selection helper". Last choise evolve or not evolve must make user.

Evolution with Lucky Egg need for fast update of user level. I have 22 level and XP increased too slow and too heavy. User have 500 XP per evolution and +500 XP if evolved pokemon is new in pokedex but Lucky egg double all expiriense. It is legal life hack =)

**Comment by Wolfsblvt** [comment]
Advanced sorting will be added. Marking/unmarking multiple as favorite too.
So I guess that will resolve nearly all of your needs?

**Comment by QuAzI** [comment]
> Advanced sorting will be added. Marking/unmarking multiple as favorite too.

Many of needs will be solved. For a begin it would be good.
