### ISSUE TITLE
"Caught with" doesn't show which pokemon from egg

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#129]
Column "Caught with" show only "Poke ball", "Great ball" and "Ultra ball" but some pokemons evolved from eggs. How can I distinguish them?

**Comment by Wolfsblvt** [comment]
Yeah, I am not sure why that's the case. We have to investigate there.

**Comment by Wolfsblvt** [comment]
Okidoki, investigated.
The PogoAPI - which we use to do the server communication - returns "Pokeball" for every Pokémon hatched from an egg. There is no chance for us to know if it was an egg or not.

So for now, we have to live with that. Can't fix it.
