### ISSUE TITLE
HOWTO:  Sorting by multiple columns

### ISSUE THREAD

**Issue by JaymerJaymer** [Wolfsblvt/BlossomsPokemonGoManager#13]
A trick for sorting that has existed for years is:
Pick your 3 columns, for example, you want to sort by, then sort them in reverse order - try it...
click on these columns:

CP
Move 2
Type 1

As it does the "next" sort, it keeps the sort order from the previous sort.

This gives you your Dex sort by
Type 1, and within that by Move 2 and CP inside that.

**Comment by ghost** [comment]
Hey thanks for the heads up! I actually had no idea it did this, but that makes a lot of sense now that I think about it. Im going to go ahead and close this issue, as technically its not a problem. However, feel free to post it to either reddit thread :)
