### ISSUE TITLE
Reduction of the displayed volume [enhancement]

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#130]
Possible width of some columns like IV, LVL, Atk, Def, Stam, CP, HP, Candies and Stardust can be decreased.

Also Candies and "To Evolve" can be joined and shown like

```
Species  | Candies\r\n
         | to evolve
---------|------------
Pidgey   | 25 / 163
Pidgeoto | 50 / 163
```

where 25 and 50 - candies for evolve and 163 - total candies count.

**Comment by Wolfsblvt** [comment]
Guess we have to rework the columns quite much with the new UI, and see if we can group some. But note: If we group columns like candies for evolve and total candies count, you can only sort after one. And how should the user know after which?

I guess the displayed volume will be reduced soon with hideable columns in #65.
