### ISSUE TITLE
Allow 'Export as CSV' or similar

### ISSUE THREAD

**Issue by EmSixTeen** [Wolfsblvt/BlossomsPokemonGoManager#131]
Would be appreciated.

edit: Should have had a better look other than just the menus.

**Comment by Wolfsblvt** [comment]
At the moment you can mark all with CTRL+A and copy with CTRL+C. Then paste whereever you wont.

Otherwise, try to use the issue search next time :P 
#63 is called "Excel/CSV export of table".
