### ISSUE TITLE
[Suggestion] Add when/where pokemon was catched?

### ISSUE THREAD

**Issue by nguyetr3** [Wolfsblvt/BlossomsPokemonGoManager#134]
where captured?

when - done
https://github.com/Blossomforth/BlossomsPokemonGoManager/pull/54

**Comment by Wolfsblvt** [comment]
We could add that, but would that really help you?

I mean it would just be an id, dunno how much you can get from it :P

**Comment by nguyetr3** [comment]
i dont know what server return, but isnt it a lat/long?

**Comment by Wolfsblvt** [comment]
I am not sure. Thought it was just a cell where the Pokémon was found, cause Niantics want to mask exact locations. Stalking issues and such.

**Comment by weblue** [comment]
niantic currently isn't returning anything for this, it's broken

**Comment by QuAzI** [comment]
> niantic currently isn't returning anything for this, it's broken

It explains why maps was removed in the game
