### ISSUE TITLE
Don't wanna launch... Java problem?

### ISSUE THREAD

**Issue by Sakugha** [Wolfsblvt/BlossomsPokemonGoManager#139]
Any solutions?
![capture](https://cloud.githubusercontent.com/assets/20083207/17526288/826a43da-5e5e-11e6-8377-5123bb3d1891.PNG)

**Comment by weblue** [comment]
Are you launching from the source?

**Comment by weblue** [comment]
could you describe the way you're launching the app?

**Comment by Sakugha** [comment]
clicking on the .jar

---

De : weblue notifications@github.com
Envoyé : mardi 9 août 2016 17:56
À : Blossomforth/BlossomsPokemonGoManager
Cc : Abdou Uchiha; Author
Objet : Re: [Blossomforth/BlossomsPokemonGoManager] Don't wanna launch... Java problem? (#139)

could you describe the way you're launching the app?

##

**Comment by Wolfsblvt** [comment]
Please check that you have Java 8 installed.

**Comment by Sakugha** [comment]
Oh okey, i have the 6 version.

---

De : Wolfsblvt notifications@github.com
Envoyé : mardi 9 août 2016 19:04
À : Blossomforth/BlossomsPokemonGoManager
Cc : Abdou Uchiha; Author
Objet : Re: [Blossomforth/BlossomsPokemonGoManager] Don't wanna launch... Java problem? (#139)

Please check that you have Java 8 installed.

##

**Comment by Wolfsblvt** [comment]
Yes. Then please install the latest version of Java, which should be Java 8. It is needed to run this app.
