### ISSUE TITLE
HP is not sorting correctly.

### ISSUE THREAD

**Issue by cinek19** [Wolfsblvt/BlossomsPokemonGoManager#140]
HP is not sorting well, take a look.

BTW thanks for this awesome tool :)

https://gyazo.com/1268577e34468540740c524544e81025

**Comment by weblue** [comment]
need to fix the comparators

**Comment by jrwinter** [comment]
This comparator should work: https://github.com/sawano/alphanumeric-comparator/blob/master/src/main/java/se/sawano/java/text/AlphanumericComparator.java

**Comment by weblue** [comment]
we already have the comparator implemented, I think it was just an oversight

**Comment by weblue** [comment]
also @jrwinter that comparator is alphanumeric so it's a bit overkill for just numbers
