### ISSUE TITLE
Transfer do not update pokemon count

### ISSUE THREAD

**Issue by rbusquet** [Wolfsblvt/BlossomsPokemonGoManager#141]
I batch transfered some pokemon with low IV, but the counter within the mobile app did not change, causing a mismatch between pokemons appearing and the number of pokemons.

Maybe a problem with the official client... But maybe some operation should be made to update this variable.

`Pokédex - Types Caught: 53, Total Pokémon Caught: 213, Total Current Pokémon: 43`

![photo_2016-08-09_14-43-49](https://cloud.githubusercontent.com/assets/7198302/17526929/b7ffd52e-5e3f-11e6-99f6-f9c9f7ea92bc.jpg)

**Comment by weblue** [comment]
You must restart your app for the changes to reflect. There is no fix for this.

**Comment by rbusquet** [comment]
Thanks, tried it and did not change. I think I just lost 9 pokemon slots...

**Comment by weblue** [comment]
to be clear though, to restart, you force closed the application from the app overview and then opened it again?

**Comment by weblue** [comment]
so you went through all the loading screens

**Comment by rbusquet** [comment]
I closed the app, deleted application data in Android settings, logged
again (twice). No update on that.

Em 9 de ago de 2016 14:55, "weblue" notifications@github.com escreveu:

**Comment by Wolfsblvt** [comment]
The numbers aren't identical all the time. No issue with neither the official app, nor our tool.
It is just that the official app counts your eggs as pokemon slots ;)
That's the 9 you are missing there.

**Comment by rbusquet** [comment]
Oh, thanks! Didn't think about that. 
Well, I can breath now, no fear of future ban haha

**Comment by weblue** [comment]
@Wolfsblvt since that counts towards the max pokemon, we should probably add eggs when we do our calcs too

**Comment by rbusquet** [comment]
Sure, showing this info would be interesting.

**Comment by Wolfsblvt** [comment]
Maybe even show something like `Total: 43 (+9 Eggs)` or something, so everone really understands it.
Yeah, @weblue already opened the issue at #142.
