### ISSUE TITLE
Count eggs in number of pokemon

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#142]
Add eggs to number of pokemon in the relevant areas

**Comment by Wolfsblvt** [comment]
@weblue Mis-using your issue now to ask/tell you something.
Could you join our discord channel if you are actively working on this project and signing issues and stuff? Just so that we are able to talk. Would be cool :P

**Comment by weblue** [comment]
I'm at work rn, I'll be on in about 4ish hours

**Comment by Wolfsblvt** [comment]
Always when I go to sleep *lol*
Just said cause you are heavily closing and answering issues here - which is really cool, it's good that others do that too - but you haven't read the latest discussions we did there etc.
For example you don't know that we will do a pre-release, etc.

And if I have questions about what you did or why, I can't ask :(

**Comment by weblue** [comment]
if you need to, message me direct on discord and I can reply when I get home

**Comment by Wolfsblvt** [comment]
It's not **that** important right now. It's just the general thing like I said. For example that you don't know the latest discussions *lol*

Also, if you go through issues and answer them, try labelling them in line with the others and what is explained in our wiki. That would mean that I don't have to add those labels later :D

**Comment by weblue** [comment]
alright, I was being a bit lazy and only labeling a couple
