### ISSUE TITLE
Count and Evolve and Transfer

### ISSUE THREAD

**Issue by ferazambuja** [Wolfsblvt/BlossomsPokemonGoManager#155]
Here is a mockup:
![saijs](https://cloud.githubusercontent.com/assets/12782082/17539420/22307570-5e7c-11e6-8419-ce1e451e5a81.jpg)

It will make it easier to decide how many can I transfer and evolve.

**Comment by Wolfsblvt** [comment]
I don't think that many people would want to Evolve every Pokémon with high evolve. That's a niche request.

But for making it easier to transfer and to decide how many and which you can evolve, there is already an issue for that: #44 

Would that help you for your request?

**Comment by ferazambuja** [comment]
Agree. The high IV is not a great idea. I forgot to remove from the mockup. 
I was thinking something like transfer after evolve "batch" for the candy Pokémon (pidgey).

**Comment by Wolfsblvt** [comment]
"Transfer after evolve" is already possible! There is a checkbox under the "File" menu you can click.
