### ISSUE TITLE
Line Spacing on 4k Screens

### ISSUE THREAD

**Issue by schwartzadev** [Wolfsblvt/BlossomsPokemonGoManager#163]
Manager works great, functionality-wise but all the lines appear to be about 50% as tall as they should be, cutting off around half of all of the lines, making everything very hard to read.
See the image below for a screenshot
![Screenshot](https://cloud.githubusercontent.com/assets/18607205/17543889/f499d1dc-5e90-11e6-9d6e-43e54d9bbaa8.PNG)

Cheers

**Comment by Wolfsblvt** [comment]
Yeah, current UI is broken on 4K resolution. Sadly there is no easy fix for that.
We are working on a new UI though, that will be available soon. Not really fast, but soon. And it will work on every resolution.

So sadly you have to wait for that :-/
Watch out issue #83 for updates on that.

**Comment by Ljaysoft** [comment]
A quick (but not really good) fix is to scale back your UI to be 1:1 (move the slider down in System->Display to 100%) It will fix the text but everything will be very small.
