### ISSUE TITLE
Stardust column offset by one

### ISSUE THREAD

**Issue by Macrike** [Wolfsblvt/BlossomsPokemonGoManager#164]
_Just creating a ticket for this for easier tracking of the issue as I originally raised it on [Reddit](https://www.reddit.com/r/PokemonGOIVs/comments/4vpep9/blossoms_pokemon_go_manager/d66psa6)._

**Version tested:** v0.1.2-alpha.1

The Stardust column does not always display the correct values as per the game. For example:
- Kakuna Level 15 / CP200 / HP52 / Stardust 1900 appears in Pokemon Go Manager as 1600
- Spearow Level 3 / CP45 / HP17 / Stardust 400 appears in Pokemon Go Manager as 200
- Growlithe Level 13 / CP452 / HP54 / Stardust 1600 appears in Pokemon Go Manager as 1300

This happens on almost half of my Pokemon. When inputting the values shown in Pokemon Go Manager into other IV calculators, no possible combinations are found.

Not sure if this is an issue with the API or with Pokemon Go Manager itself, but it seems like the way Stardust cost is being calculated may be incorrect. In fact, I'd say that all values in the Stardust column are offset by one level, but because some levels have the same Stardust cost, it's only apparent on those levels where the Stardust cost increases (e.g. levels 3, 5, 7, 9, 11, etc.). A quick check at the Pokemon levels of those affected confirms this theory.

Below is a link to the table with the Stardust cost for each level as per the game.

https://docs.google.com/spreadsheets/d/118FlgG9YMrU6Ae74cwuhl_AXyEv0QEw9A7Pfvo8MJYI/edit?usp=sharing

**Comment by Purely-Imaginary** [comment]
It's on API side of application - they commited fix it already, they will merge it in when Grover-c13 will have time.

**Comment by Wolfsblvt** [comment]
That means I can close here. Nothing more than waiting possible.
