### ISSUE TITLE
Bug with renaming.

### ISSUE THREAD

**Issue by juemrami** [Wolfsblvt/BlossomsPokemonGoManager#169]
im trying to rename my pokemon using 
%ivrating%%name%
while it will do most of them it gives me error name invalid on a couple i beleive that its doing this on the pokemon with longer names as its trying to spell out thier whole name and add characters behind that which is past the character  limit

maybe you guys could look into having it cutoff names as soon as they reach past the amount of character permited.

**Comment by Wolfsblvt** [comment]
Yeah, mentioned at #168. Will fix that. Cut-off is the best option, I would say.
