### ISSUE TITLE
how to inser iv value

### ISSUE THREAD

**Issue by jaxjaxjaxjax** [Wolfsblvt/BlossomsPokemonGoManager#171]
where i should input iv value there is no place to input

**Comment by Wolfsblvt** [comment]
What do you mean exactly? Can you specify what you want to do?

**Comment by jaxjaxjaxjax** [comment]
![image](https://cloud.githubusercontent.com/assets/20953970/17562929/4604a026-5f57-11e6-8d49-bfeebfee6745.png)
where i should input iv value??

**Comment by Wolfsblvt** [comment]
Ah. I understand. Guess the window is too small for you :D 
There is a very very small textbox left of that button. If you resize the window a bit, you will see it.

**Comment by jaxjaxjaxjax** [comment]
oh thank dude
