### ISSUE TITLE
Problem with %max_cp% Pattern

### ISSUE THREAD

**Issue by Carlosjrlu** [Wolfsblvt/BlossomsPokemonGoManager#172]
When I try to use the %max_cp% pattern in the rename feature, it just name the pokemon as %max_cp% not showing the value.
![image](https://cloud.githubusercontent.com/assets/20954701/17564102/ef959844-5ef7-11e6-854e-ae6a3477a013.png)

Just created an account to help a little bit with this project, at least with bug reporting.

**Comment by Wolfsblvt** [comment]
Yep. It's a problem with our replacing regex. Fixed that with #159 already.
