### ISSUE TITLE
Renaming suggestion - Total IV

### ISSUE THREAD

**Issue by kasagon** [Wolfsblvt/BlossomsPokemonGoManager#175]
Hello, 

I have two small suggestions for the renaming patterns:
- A pattern for the IV percentage, rounded down like: 100% , 091% , 052% (the 0 in front of it for making it easy to sort on name)
- A pattern for the total IV, so the total of Attack + Defense + Stamina.

**Comment by Wolfsblvt** [comment]
There is a pattern for IVs together that is like "15/7/13", but that's not what you want, right? Cause you can't sort after it.

The rounded iv percentage is already planned. For the sum.. we'll see. Too many replacements will overblow it a bit. But why not. I'll see if I add it.

**Comment by finalmakerr** [comment]
Thank you for this wonderful application!

Is it possible to have a rename pattern for the quick and special move type?
I don't think it's even visible at all in the application.

For example:
WW (Both attacks are water type)
FT (Quick attack is Fire, Secondary is Fighting)
EN (Quick attack is Electric, Secondary is Normal)

**Comment by Wolfsblvt** [comment]
Sounds interesting. I don't think it will hurt to add that. I'll consider that.

**Comment by QuadTog** [comment]
I believe the best format for this would be the following:
IV%%moveType1DPS%%moveType2DPS%
100Wa10Wa23

I've even seen one that uses hexdecimal for IV's since it enables you to represent them with 3 varchars: 9AF=9/10/15.

**Comment by Wolfsblvt** [comment]
Finished the PR, so this should be done here.

**Comment by finalmakerr** [comment]
Well done!
And thanks ;)
