### ISSUE TITLE
Sort by don't work correctly on some columns

### ISSUE THREAD

**Issue by MatBart** [Wolfsblvt/BlossomsPokemonGoManager#176]
Columns Lvl, Atk, Def, Stam, HP, To evolve, seems to be stored as String and not number.
So order by give strange results, like 10, 100, 101, 11, 20, ...

Columns CP, stardust, and IV% seems correct.

**Comment by Wolfsblvt** [comment]
"To Evolve" was broken and is fixed now.
The rest... works for me. Do you use the latest release version?
Check if you have `v0.1.2-alpha.1`.

**Comment by MatBart** [comment]
Seems fixed in last version 0.1.2, i was on .1.1

**Comment by Wolfsblvt** [comment]
Yeps (:
