### ISSUE TITLE
(minor) Check for invalid rename in bpgom

### ISSUE THREAD

**Issue by patrissimo** [Wolfsblvt/BlossomsPokemonGoManager#179]
Max pokemon nickname length appears to be 12 characters. I haven't found characters that fail yet, those may exist too and are worth checking for. In rename dialog, validate that new nick is <= 12 chars before attempting rename/closing dialog. Very minor but very easy.

You don't need to handle length for interpolated stuff (%%), that's too complex, can just let the user see on the error log which failed.

**Comment by Wolfsblvt** [comment]
Yeah, was mentioned in #168. Will be fixed soon.
