### ISSUE TITLE
Can only batch transfer once per launch

### ISSUE THREAD

**Issue by jacketjack** [Wolfsblvt/BlossomsPokemonGoManager#18]
Each time after I use batch transfer, I am unable to use it (batch transfer) again unless I restart. Anyways great app and thank you!

**Comment by Scott7789** [comment]
Same issue. I can't remember what life was like before this program. You have a fan for life.

**Comment by weblue** [comment]
It's been fixed already, release is soon

**Comment by wullxz** [comment]
@weblue do you know what caused it?  
I also experienced that bug but I guess the source already has the fix, right?  
What was the fix?

**Comment by masiarb** [comment]
This has already been addressed in #9 and apparently already fixed :).

**Comment by weblue** [comment]
@wullxz so sassy

**Comment by ghost** [comment]
It was the swingworker that i was using. I didnt re-create it whenever the button is pressed, but rather pre-created it on initialization,, and they could only be used once, apparently! haha.
