### ISSUE TITLE
Graphical issue on OSX (MBPr13")

### ISSUE THREAD

**Issue by vtcifer** [Wolfsblvt/BlossomsPokemonGoManager#184]
jvm 1.8.0_60
OSX 10.11.6

Even on full screen, there's some graphical issues with the buttons  I _assume_ the tiny wedge between "Toggle Favorite" and "Select Pokemon < IV" is where I should fill in the IV value, but it's too small to show anything:

![image](https://cloud.githubusercontent.com/assets/12104547/17577274/b5ed1606-5f49-11e6-9879-992cb2480495.png)

Even worse when smaller:

![image](https://cloud.githubusercontent.com/assets/12104547/17577291/dd620f20-5f49-11e6-978f-1006315363bf.png)

**Comment by Wolfsblvt** [comment]
Yep. that's a known problem. Will be fixed with the new UI hopefully.
Keep track for it here: #83
