### ISSUE TITLE
Error while renaming some Pokémon

### ISSUE THREAD

**Issue by thomashaentjens** [Wolfsblvt/BlossomsPokemonGoManager#191]
Hi,

I had this Error message while renaming : 

```
[08/11 10:13:11]: API Error while renaming Nidorina()!
[08/11 10:13:11]: [Ljava.lang.StackTraceElement;@7890d183
```

it happens while renaming all my Pokémon then i tried to rename it alone and it worked

had the same here : 

```
[08/11 10:30:17]: API Error while renaming Tadmorv()!
[08/11 10:30:17]: [Ljava.lang.StackTraceElement;@713a6c05
```

again it worked while renaming alone

so tried to switch back to english and ...

```
[08/11 10:32:07]: API Error while renaming Horsea()!
[08/11 10:32:07]: [Ljava.lang.StackTraceElement;@1a397746
```

and again worked while renaming alone.

for information the number of renaming that worked before the error was variable.
1st time : 18/69
2nd time : 16/16
3rd time : 10/19
4th time : 15/19

**Comment by Wolfsblvt** [comment]
What name did you choose for renaming?Something that will be long for some Pokémon?
Pokémon names are limited to 12 characters, and there is a bug currently where it throws an error if the name is longer.
It is fixed for the next version already with #190.

**Comment by thomashaentjens** [comment]
Hi there, no the name was %iv% so it's max 12 characters

**Comment by thomashaentjens** [comment]
Yes just %iv% so it can go from "0 / 0 / 0" ( 9 characters ) to "15 / 15 / 15" ( 12 characters)

**Comment by Wolfsblvt** [comment]
Maybe the queries timed out. Have you tried it again?

**Comment by thomashaentjens** [comment]
Ok, I just tried back with 46 renaming using %name_4%-%iv_rating% and it went through so i guess it was not a real bug and the queries just timed out.

**Comment by Wolfsblvt** [comment]
Yeah, it often happens when the servers are busy.
