### ISSUE TITLE
The %ivrating% on rename is not working

### ISSUE THREAD

**Issue by brunoarocha** [Wolfsblvt/BlossomsPokemonGoManager#197]

**Comment by BlasterM2A** [comment]
@brunoarocha  (Maybe) You have mistyped it... is %iv_rating% and work for me

**Comment by sebium** [comment]
In fact, %ivrating% work well, but we have an error when the name is too long.

for example : 
- %ivrating%_a  work well 
- %ivrating%_%name% doesn't work if the name is too long.

Remark for the development team : may be, It will better to give the possibility to edit the number of decimal of ivrating (2 decimals after the "." it's too long)

**Comment by Wolfsblvt** [comment]
If %ivrating% works you are not using the latest release version :D 
For too long names, we have fixed it already, will be in the next version.

**Comment by brunoarocha** [comment]
I guess the problem was the length. Thank you!
If the pokemon name is 6 length is OK, 7 NOT.

I agree with @sebium! It would be nice if the IV was without decimal places!

**Comment by Wolfsblvt** [comment]
Will be added too soon. With the next version.
