### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ivanders21** [Wolfsblvt/BlossomsPokemonGoManager#198]
how to install?
i dont understand, already read the readme.
it said failed to find java
thanks

**Comment by sebium** [comment]
you have to install java ( https://www.java.com )

**Comment by Wolfsblvt** [comment]
Yep, read the latest [Installation guideline](https://github.com/Blossomforth/BlossomsPokemonGoManager#installation--usage) here on GitHub.
