### ISSUE TITLE
not working on windows 10 ?

### ISSUE THREAD

**Issue by ghost** [Wolfsblvt/BlossomsPokemonGoManager#2]
hi, 

what requirements of java needed to run this program? after saving credentials its nothing happened?

**Comment by weblue** [comment]
it takes a second after credentials go through. I'm not sure if the program has a timeout handler

**Comment by wullxz** [comment]
I'm also on windows 10 and can run it just fine. The source suggests that JRE 8 is needed.
If you're still on an older version, upgrade your java installation to the latest version.

**Comment by weblue** [comment]
Suggesting to close this
