### ISSUE TITLE
Suggestion: Evolve+transfer setting

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#20]
adding a checkbox to a menu for evolving and transferring right after

**Comment by ghost** [comment]
Hey thats a fantastic idea! Just to be sure, are you making a request, or saying that you're going to implement it yourself?

**Comment by weblue** [comment]
I'll be able to implement it after I fix the conflicts in #19. I will generally submit suggestions before implementing in case others don't agree with the idea or a suggestion is going in a different direction

**Comment by weblue** [comment]
@Blossomforth Should the setting save or revert to not transferring after evolving on launch?

**Comment by ghost** [comment]
Ooh, i dont know. On one hand, it'd be a pain to have to select the option every time you boot the app, but on the other, you dont want to accidentally transfer your 98% dratini after evolving on accident.

What if, instead, theres 3 buttons when confirming an evolve. 
"Ok" for confirming
"Evolve And Tranfer" which causes the selection to be evolved, and then transfered,
and then of course, "Cancel", to cancel.

What do you think? It doesnt add any additional clicks. Though mis-clicks would be a pain... We coudl always add a secondary confirmation window just to make sure the user wants to evolve and transfer?

**Comment by weblue** [comment]
I'm wondering if it would be that bad for users to reselect during start up. If you're doing transfer after evolve it's probably an edge case considering you'd only be doing it after stocking up on pidgeys, rattatas, weedles, caterpies, etc.

**Comment by ghost** [comment]
Yeah, i'd agree, in that case!

**Comment by weblue** [comment]
added
