### ISSUE TITLE
[REQUEST] Truncate names/IV when attempted nickname is too long

### ISSUE THREAD

**Issue by Broly-Dev** [Wolfsblvt/BlossomsPokemonGoManager#200]
E.g. the pokemon is a Dragonite and the user inputs %name%_%ivrating% but the app responds error because the name would be too long.

I propose either truncating the pokemon name e.g. Drago_98.07 or rounding up the IV value to the nearest whole number (saving 3 character spaces in the nickname)

**Comment by Zemlor** [comment]
I personally would like the option to round %ivrating% automatically. I like having high IV's but I don't care if 95.56 rounds up to 96, and it would make it fit a lot easier in all of their names.

**Comment by Wolfsblvt** [comment]
There are three things for that that got already implemented.
First, the tool cuts nicknames after 12 letters automatically now. Seconds, you can use `%name_4%` or `%name_6%` for shorter version of the name. Third, there is an option for the rounded IV, with `%iv_rating_int%`.
