### ISSUE TITLE
max cp (CUR) not accurate?

### ISSUE THREAD

**Issue by heIlo** [Wolfsblvt/BlossomsPokemonGoManager#204]
![bug](https://cloud.githubusercontent.com/assets/13257896/17609167/dd659872-6064-11e6-98e2-e3466861b15a.jpg)

there's about 50 points of value difference

**Comment by Wolfsblvt** [comment]
Can you tell me your trainer level? Is it 22? Or 23?
EDIT:// And guess you are using the latest alpha release?

**Comment by Wolfsblvt** [comment]
Okay, checked the function and my Pokémon. It's really strange. I a, quite sure that you can level your Pokémon **exactly** `1.5` levels above your trainer level. Which would be a `.5` number. Yours isn't.

**Comment by heIlo** [comment]
hmm, that's really weird. I'm level 23... 
yes i am using the latest alpha release. according to pogo i can't upgrade my dragonite further. which is extremely weird. perhaps it's just a fringe case with me. hopefully others can chime in, as i don't have enough stardust to get another max cp cur :/

**Comment by Wolfsblvt** [comment]
Will check that more detailed. Thank you for the report.
I mean there seems to be a bug somewhere, that's for sure :D

**Comment by Wolfsblvt** [comment]
Talked to some people. Limit should totally be `trainerLevel + 1.5`. Nothing has changed.
I have the slight feeling that this _may_ be a bug in PokémonGo itself that let you level-up one more time.

But I don't know. Can you check some other pokemon and report back later?
The other guys said too that we need further proof that there is something too.

Will mark that as pending again.

**Comment by kagamihiiragi17** [comment]
For what it's worth, I also have this exact issue with a Gyarados.  It's 2.0 levels above my trainer level.  Could be an issue within Pokemon Go.

**Comment by xephael** [comment]
I believe this is a Pokemon Go glitch, I'm also able to level Pokemon above the expected level cap by one power up.

**Comment by heIlo** [comment]
I've just levelled another vaporeon to max. This time, I can't level it up past trainerlevel+1.5. i think this is a GO bug.

**Comment by finalmakerr** [comment]
![capture](https://cloud.githubusercontent.com/assets/7450109/18267405/9c814316-7427-11e6-8fae-9706d10a7746.PNG)

Using Version: v0.1.2-alpha.2

**Comment by Wolfsblvt** [comment]
Same point here. Dunno what we can do. There is no information on when yoiu can level the pokemon higher than it should be possible.
