### ISSUE TITLE
Need to support 1.8+

### ISSUE THREAD

**Issue by ValorRed** [Wolfsblvt/BlossomsPokemonGoManager#207]
![image](https://cloud.githubusercontent.com/assets/20829876/17611624/f92fa848-6016-11e6-8242-c9f189ad9ef3.png)

**Comment by Wolfsblvt** [comment]
That's really strange. We require Java 8. That's the thing. When does that error occur?
Looks for me like a faulty Java installation. Can you deinstall and reinstall the newest version again?

**Comment by ValorRed** [comment]
My bad. It's my JDK environment corrupted. Reinstall, then it worked. But seems not working behind the proxy. Will raise another issue.
