### ISSUE TITLE
Does not work behind a proxy

### ISSUE THREAD

**Issue by ValorRed** [Wolfsblvt/BlossomsPokemonGoManager#208]
Tried to login, give authentication fail.
Behind HTTP proxy.

Thanks

**Comment by Wolfsblvt** [comment]
Yes, that is possible. It also doesn't work behind some Firewalls or in working networks.
I don't really know why, but I am not sure how that can be fixed, or if even.

**Comment by xephael** [comment]
It's possible google is blocking basic proxies. On a sort of side note I'd recomend not logging in through a proxy because they seem to be related to permabans (presumably because other people are on the same proxy and botting.)

**Comment by Lacero** [comment]
I think what @torin555 wrote has some merit. Nothing against ToS about using a proxy server but Niantic could well consider it a factor to look more closely at accounts using one.

**Comment by ValorRed** [comment]
My company has a HTTP proxy for outgoing traffic. Just wanna be able to use it in office. Can we please have this feature?

**Comment by xephael** [comment]
Does the normal pogo app work properly behind that proxy?

**Comment by ValorRed** [comment]
Yes. First my android tablet WiFi setting allow me to setup proxy. then the game just work. 

I tried PokeBuddy, it will automatically take my Win7 Internet Option proxy settings. 

NecroBot, just put proxy setting in auth.json, I will work.

**Comment by Wolfsblvt** [comment]
We use the [PokeGo-API by Grover](https://github.com/Grover-c13/PokeGOAPI-Java), which handles the authentication.
Can you maybe step over there and ask if they support proxies?

**Comment by ValorRed** [comment]
Proxy is th infrastructure of connection. Nothing to do wi Pokémon API. 
You ca see from this post that someone else do use proxy. The problem they resolved had nothing to do with proxy. But proxy I supposed to work. Our proxy does no need authentication, it is supposed to be simpler.

 https://github.com/Grover-c13/PokeGOAPI-Java/issues/295

**Comment by Wolfsblvt** [comment]
It isn't solved in your linked issue. That's the point.
We do not do any real login stuff ourselves. We use the authentication methods that the PokeGo-API provides us.
That's what I was saying.

**Comment by ValorRed** [comment]
But you do provide a connection, right?

The proxy is part of internet connection.

**Comment by Wolfsblvt** [comment]
I do not understand what you mean. Every request to the google server for the login, and every other request to the API is handled by the PokeGo-API. We use their utility functions. They manage the connections and stuff.

**Comment by adrian-wong** [comment]
This is more of a user config than a bug.  Just add -D proxy options in your RunOnWindows.bat

-Dhttp.proxyHost=<proxy_host or ip> -Dhttp.proxyPort=<proxy_port> -Dhttps.proxyHost=<proxy_host or ip> -Dhttps.proxyPort=<proxy_port>

i.e. RunOnWindows.bat:
start javaw -Dhttp.proxyHost=proxy.mycompany.corp -Dhttp.proxyPort=8005 -Dhttps.proxyHost=proxy.mycompany.corp -Dhttps.proxyPort=8005-jar BlossomsPogoManager.jar

**Comment by Wolfsblvt** [comment]
Didn't know you have to explicity specify the proxy in Java. Good thing!
Then this can be closed here.
