### ISSUE TITLE
very very useful , best currently 

### ISSUE THREAD

**Issue by Luc4z** [Wolfsblvt/BlossomsPokemonGoManager#21]
nice , simple , clean UI .

still , it would be awesom if we can use item such as incense/luck egg would also be great.

and should add:
pokemon list refresh button
should show candies if there's evolve button
totall pokemon's counts

**Comment by ghost** [comment]
Lucky egg support is definitely a planned feature, I'm not so sure about incense though. Currently the program doesnt do anything else, in fact it never even sets the latlong! Using an incense within the app would be a waste of incense. Can you clarify further on a good use case for being able to use incense in this app?

**Comment by wullxz** [comment]
I already implemented a refresh button for the Pokemon list in PR #14.  
It's not merged though but will be soon.

**Comment by norecha** [comment]
@Blossomforth Is it a good idea to not send coordinates at all? That would be different than what original app is doing. You are not defaulting to something else right?

**Comment by OSwoboda** [comment]
@norecha I don't think that is a problem, because you can use the app with GPS turned off and evolve/send Pokémon away.

**Comment by Luc4z** [comment]
@Blossomforth incense would be great because since i found this tool , i always use this tool while im botting ,so it would be awesome if we can use it manually if we want to , just a request tho , i can't tell its needed or not but it could make it more convience .

@wullxz thanks man i didn't look at pull request

**Comment by Wolfsblvt** [comment]
- pokemon list refresh button  
  **Already added**
- should show candies if there's evolve button  
  **Candies to Evolve is a column for each pokemon, and also how much candies you have. That should be enough?**
- totall pokemon's counts  
  **Is already displayed in the console**

Lucky egg support is asked here #5 And incense... guess we'll see.

Hope it's okay if I will close this issue then?
