### ISSUE TITLE
Rename by IV rating with whole numbers only.

### ISSUE THREAD

**Issue by Angelarius** [Wolfsblvt/BlossomsPokemonGoManager#214]
It would be nice to be able to use only whole numbers (rounding up or down would be even nicer) when batch renaming by %ivrating%

**Comment by Wolfsblvt** [comment]
Rounded IV is already implemented and will be part of the next release.
I even made some more additions to similar columns. See #209 for example.

**Comment by Angelarius** [comment]
Thank you, sorry for duplicate. Navigating github is proving challenging for me.

**Comment by Wolfsblvt** [comment]
Try using that search bar at the top under the issues tab, with some keywords that may be part of the issue.

But it's really no big problem. Just open issues when you have something. I will remember if we have something like that, and answer. Closing isn't such a big deal if it already exists. Better that than missing a report that may need fixing :P
