### ISSUE TITLE
Renaming Errors

### ISSUE THREAD

**Issue by aphrospice** [Wolfsblvt/BlossomsPokemonGoManager#215]
Renaming with patterns causes errors.

Using regular text works.

Please advise.

![untitled](https://cloud.githubusercontent.com/assets/20994881/17629373/0164a8c6-6088-11e6-920e-33f638e39400.png)

**Comment by Wolfsblvt** [comment]
Your nickname is too long. The game only accepts up to 12 characters.
It is already fixed for development (See #190) and will be part of the next release.

**Comment by aphrospice** [comment]
Ok so please post a string that would work no matter how little pattern I use, ie %name% %iv% I get errors. Thanks.

**Comment by weblue** [comment]
try just %iv%; we should probably add patterns to limit the length of pokemon species name

**Comment by aphrospice** [comment]
Ok, I tried that and it is adding random numbers like 0/3/15. Please advise.
How do I bulk erase those random numbers?

I am trying to just rename my pokemon, i.e. Jigglypuff 98

**Comment by Wolfsblvt** [comment]
@weblue  We have that already, look at the code :P 

@aphrospice:
Try pattern `%IVRATING%`, that just makes a number like `98.14`, which is with decimals.
For the short name and stuff you have to wait for the next release.

**Comment by weblue** [comment]
idk who decided to create an 8 character iv field as the default for %iv%
%ivrating% also sounds exactly the same. We should probably revisit this design with UX in mind

**Comment by aphrospice** [comment]
Thank you guys, now my game is back to normal!

I didnt even see ivrating, next time I'll look more closely.

Thanks again

**Comment by Wolfsblvt** [comment]
@weblue Those patterns were reworked days ago. You can check out the latest version :D
