### ISSUE TITLE
opening browser for token not working under Plasma 5

### ISSUE THREAD

**Issue by thisischrys** [Wolfsblvt/BlossomsPokemonGoManager#22]
google login type > opening site errors out on this
(java:2482): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
no site opens

**Comment by weblue** [comment]
that's a browser issue, not an issue with the program

adding a "if the link doesn't open in x seconds, click here" functionality might be useful for people who end up getting browser issues though

**Comment by thisischrys** [comment]
this was in chrome
also tried firefox, no output, still not working
guess I'll just run this in a vm for now
