### ISSUE TITLE
Delay option between transfers and evolutions [enhancement]

### ISSUE THREAD

**Issue by ChiIIerr** [Wolfsblvt/BlossomsPokemonGoManager#220]
With the recent ban wave that happened today, a lot of attention will be pulled to delays happening between calls. Having a clear option to select how much time between actions would greatly benefit the tool. Thanks!

**Comment by xephael** [comment]
This is already implemented in the development branch.

**Comment by Wolfsblvt** [comment]
Yep, wil be released soon.
