### ISSUE TITLE
Doesn't load after logging in half the time

### ISSUE THREAD

**Issue by Lacero** [Wolfsblvt/BlossomsPokemonGoManager#221]
I'm using Windows 7 and PTC account. About half the time I log in, nothing happens. No logging in source code that I saw so I can't pinpoint the issue. Interestingly, program is more likely to load when running in a sandbox environment. I'm using Sandboxie 3.66. Got an error only the first time I ever used it.

![image](https://cloud.githubusercontent.com/assets/20910359/17639372/7aceafc2-60bf-11e6-8ce0-5e7b8be40f35.png)

**Comment by xephael** [comment]
When you say nothing happens what do you mean? Do you mean the window doesn't open, the pokemon list is empty, something else? And if the pokemon list is empty, what does the console at the bottom say?

**Comment by Wolfsblvt** [comment]
Good questions. This issue is new to me.

**Comment by Wolfsblvt** [comment]
@Lacero can you give an update here?

**Comment by Lacero** [comment]
What I mean is, I type in the username and password and click on "Use PTC Auth" and then nothing happens. I never get the option to save the password or see the UI, nor do I get the login has failed message. The javaw.exe remains listed in the task manager and if I get several failures in a row, I get several JVMs doing nothing.

**Comment by Wolfsblvt** [comment]
Are you using the latest alpha release?
We got several login problems with the old version that got fixed.

**Comment by Lacero** [comment]
No, I had been using 0.1.1-Beta. I tried 0.1.2-alpha today and got it running (working) but with this error in the console log:

Unable to login!
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
    at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
which continues for 8 more calls

**Comment by Wolfsblvt** [comment]
That's happens a lot with the PokeGo-API we use. We are not sure where this bug comes from, sadly :-/
Does the tool work though? Or is this exception preventing it from working?

Most of the time it just means the server hasn't responded for that particular call.

**Comment by Lacero** [comment]
I see, thanks for explaining. Tool does work. All I try to do is check IVs and sort by the different columns but that is enough.

**Comment by Wolfsblvt** [comment]
Then I'll close here. We have other issues open concerning the same bug with similar problems. So it will not get forgotten :P
