### ISSUE TITLE
Make the popup displaying successful transfer of Pokémon a configurable option

### ISSUE THREAD

**Issue by jabberjabber** [Wolfsblvt/BlossomsPokemonGoManager#223]
It's really annoying and all the info is in the bottom bar already so what is the purpose of the pop up.

**Comment by Wolfsblvt** [comment]
Some people may do big bulk operations with hundreds of Pokémon.
Why should they have to scroll through the whole log to see if there were errors und how many?
The summary is easily disposable with hitting Enter key

**Comment by jabberjabber** [comment]
Then just put whatever text that was in the pop up at the end of the log in the bottom box also. I transfer in little chunks at a time, and that extra box is super annoying.

**Comment by Wolfsblvt** [comment]
Could be a settings toggle later maybe.
"Do not show bulk finishes window"

**Comment by jabberjabber** [comment]
Thank you.

**Comment by Wolfsblvt** [comment]
Was added with linked PR.
