### ISSUE TITLE
Issue with number of candies when  evolving

### ISSUE THREAD

**Issue by kargrim** [Wolfsblvt/BlossomsPokemonGoManager#23]
Hello,

First of all, thanks for your great tool. It's everything i've been looking for.

I've spotted a minor error when evolving pokemons : In the "text" frame, there seems to be an issue when writting the number of candies to substract :+1: 
_[08/03 17:49:43]: Evolving Rattata. Evolve result: Success!
[08/03 17:49:43]: Stat changes: (Candies: 40[-24], CP: 805[+505], HP: 72[+31])_

It says 24 but Rattata takes 25 candies to evolve. Same issue with Pidgey where it says 11 instead of 12. I guess it will be the same for all of them.

Thanks again and keep up the good work !

Kargrim

**Comment by Ljaysoft** [comment]
I just fixed it. doing a pull request as we speak
