### ISSUE TITLE
Add %ivround% and %ivsum% to rename

### ISSUE THREAD

**Issue by mreinhardt** [Wolfsblvt/BlossomsPokemonGoManager#230]
Values like `96.86` and `12/13/15` aren't as useful as `97` (96.86 rounded) and `40` (12/13/15 summed) for renaming in most instances. It would be useful to have `%ivround%` and `%ivsum%` as rename variable replacements.

**Comment by Wolfsblvt** [comment]
At least rounded iv exists in the next release. Sum is not needed then I would say, cause it holds exactly the same information with exactly the same characters.
