### ISSUE TITLE
File not responding

### ISSUE THREAD

**Issue by deancarloz** [Wolfsblvt/BlossomsPokemonGoManager#237]
Hu guys, every time I open blossompogomanager it crushes.
Do you guys have any idea why?
![error](https://cloud.githubusercontent.com/assets/21025022/17650681/e052becc-6229-11e6-9928-942f23d03a1a.jpg)

**Comment by Wolfsblvt** [comment]
Seems like you are using the old beta version. Try the new alpha version if possible.
Also check if you have the latest version of Java installed. Maybe post which version you have.

But guess it's a bug related to the old version. We fixed that.

**Comment by Wolfsblvt** [comment]
Tried that?
There is no feedback from you so I'll close here.
If it is still a problem, just answer here.
