### ISSUE TITLE
Suggestion: Allow rename to also bulk/individually remove Nicknames

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#247]
Currently, we can bulk rename. Theres no way to remove the nickname(s) in case we want clean/removed nicknames. Putting an empty string in the UI doesn't allow the process to go through. Putting an empty space, makes the nick name " " (empty space). You can see this when you sort by nicknames.

**Comment by QuadTog** [comment]
Just curious but why would you ever want to name them nothing?

**Comment by Wolfsblvt** [comment]
That you can't reset a nickname with empty string is already fixed and will be part of the next version.
