### ISSUE TITLE
Wont Allow Me To Paste the Google Authetication Code

### ISSUE THREAD

**Issue by TheRealYogiBear** [Wolfsblvt/BlossomsPokemonGoManager#248]
It will allow me to run the app and copy the google authentication code but it will not allow me to paste it into the required section. If I type in the code manually none of my info pops up. Wondering if I am doing something wrong or it is a small glitch in the system

**Comment by Wolfsblvt** [comment]
Are you using the latest alpha release version?
We fixed a lot of login errors.
That you can't paste the code seems really strange to me.

**Comment by steveuhoh** [comment]
Having the same issue, app works but I cannot paste the auth. code from google. Alpha version installed. Not sure if it matter but i tried using Internet Explorer and Mozilla FireFox as web browsers to copy the auth. code i could copy from both but neither allowed me to paste. Also Java is updated.

**Comment by Wolfsblvt** [comment]
Really guys, if you have trouble to do something with the app from an external point, could you tell us which Operating System you use? :P 

Seems like Ubunto for example forbids copying to Java as a policy by default.

**Comment by steveuhoh** [comment]
windows 7 home premium

**Comment by Wolfsblvt** [comment]
Can you do me a big favor, @steveuhoh?
Look at [this Stackoverflow answer](http://stackoverflow.com/a/8513761/2505580) and try it out. If it works, that would tell us what the solution is.

**Comment by steveuhoh** [comment]
i was just ooking at this actually, i will give it a shot and report back
Update: Windows explorer is constantly not responding and restarting when i try to paste the java.policy fie in my user file. I tried this method http://www.shodor.org/interactivate/resources/InstructionsCopyPaste
with no success, but i do believe this is the source of the problem.

**Comment by steveuhoh** [comment]
Tried manually entering the auth. code again and it worked...so problem half solved i suppose, but this java issue is gonna drive me nuts now lol

**Comment by Wolfsblvt** [comment]
That is really strange, yes. Seems like some weird Java problem forbidding to paste something that was copied in clipboard from the outside.
I will keep this issue open a bit, maybe I have time to google round too.

Otherwise would be cool if you try and test some more things that may work.

**Comment by steveuhoh** [comment]
tried running malwarebytes and hitmanpro followed by combofix and im still getting the same windows explorer issue, ill have another run at it tomorrow night, until then manual input works fine if you input the correct auth code, great app.

**Comment by steveuhoh** [comment]
Well, copy and paste still isn't working, however highlighting the auth. Code then drag and dropping works! Maybe the OP can try that and let us know if it worked for him as well.

**Comment by Wolfsblvt** [comment]
It's still strange that Copy&Paste is not working. I will keep this issue open and see if I have time to check it sometime soon.
Otherwise guess we will have to live with that problem :-/

**Comment by selabie68** [comment]
I think this issue may be related to a Right-Click bug. You cannot right click in the JTextField you should still be able to use `Ctrl + V` to paste

**Comment by Wolfsblvt** [comment]
No one else with this issue. So gonna close it.
