### ISSUE TITLE
Transfer window not adjusted for display

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#251]
If many records selected window greater than my display

![_2016-08-15_10 08 26_10 08rrrrrrr](https://cloud.githubusercontent.com/assets/1897605/17658535/0cd500a8-62d5-11e6-9656-df93b9d1154a.png)

Also window has no parent and can be hidden under main form.

**Comment by Wolfsblvt** [comment]
Yeah, bug is known. Has to be fixed I guess, even if the new GUI is coming.

**Comment by QuAzI** [comment]
Do you have an approximate plan of releases? Time is interesting

**Comment by Wolfsblvt** [comment]
No. We all do that as a hobby, so we usually invest time when we have it and feel like it. That makes every exact plan not useful.
But I can tell you that there will be a new release this week, I would say even wednesday or earlier.

**Comment by nibewiahn** [comment]
Keep up the good work wolf...so far the best app

**Comment by Wolfsblvt** [comment]
Finally fixed here!
