### ISSUE TITLE
Renaming Error

### ISSUE THREAD

**Issue by Spedwards** [Wolfsblvt/BlossomsPokemonGoManager#252]
Tried renaming a handful of my Pokemon using the patterns and got an identical error on each of them.

```
[08/15 21:00:02]: Doing Rename 1 of 13
[08/15 21:00:02]: Renaming Ekans failed! Code: ERROR_INVALID_NICKNAME; Nick: %iv_stam% / %iv_att% / %iv_def%
```

Either the instructions for the name aren't clear/incorrect, are something is going wrong in the code.

**Comment by underko** [comment]
I think it's caused by a nickname length limit of 12 characters.

**Comment by Wolfsblvt** [comment]
Yep, the limit is 12 characters.
Will be fixed in future updates, the name will be cut off then.
