### ISSUE TITLE
Feature Request: CP fully evolved (current pokemon level, not max player level)

### ISSUE THREAD

**Issue by wararjey** [Wolfsblvt/BlossomsPokemonGoManager#253]
There is a column that shows the max cp (cur) for a fully evolved pokemon. However, that value seems to assume the pokemon will be fully powered up after evolving. There are several pokemon species a player would not want to invest additional stardust into (Pidgey, Weedle, Caterpie, etc.). However, it would be worthwile to know in advance, how many CP a fully evolved Pidgeot could have in order to keep on or two Pidgeys/Pidgeottos to evolve into a Pidgeot later. There might be other uses cases, where it could be important to know how many CP a certain pokemon would have after evolving.

Regards,
wararjey

**Comment by Wolfsblvt** [comment]
Good points there. I myself usually check if my Machoke with high CP is actually better than my best Machop, or something similiar.
Well be done.

**Comment by Wolfsblvt** [comment]
PR pending for that: #262

**Comment by Wolfsblvt** [comment]
PR got merged, so feature is done (:

**Comment by wararjey** [comment]
Just did a quick test of the devel branch, seems to work nicely. Thank you very much :-)
