### ISSUE TITLE
Does this tool need to send Niantic server location information through the API, before getting the pokemon holding back?

### ISSUE THREAD

**Issue by ValorRed** [Wolfsblvt/BlossomsPokemonGoManager#257]
I heard every API call need to send coordinates.
If yes, it's better to have a box to input Lat/Long, otherwise, it is easy to get banned.

**Comment by xephael** [comment]
No I don't believe a location is being sent, or if one is, it's being sent as NaN. AKA What the server would receive when you log in to the app with gps turned off.

**Comment by Wolfsblvt** [comment]
Correct. We do not send any location data to the API, and I am quite sure we never will.
It's like as iff your app shows that "GPS not found".
