### ISSUE TITLE
Installed but get nothing but Java / "BlossomsPoGoManager" in MenuBar on Mac

### ISSUE THREAD

**Issue by ej8** [Wolfsblvt/BlossomsPokemonGoManager#258]
See attached.  If I click on the Java icon in the dock the header on my Mac reads "BlossomsPoGoManager" but there is nothing else.  No screen below.  No app.  Am I doing something wrong?

<img width="843" alt="screenshot 2016-08-15 17 38 37" src="https://cloud.githubusercontent.com/assets/16333236/17680670/5ad72d50-630f-11e6-9f91-15e78da76bc1.png">

**Comment by xephael** [comment]
Hmm, odd issue that sounds similar to one on here recently, do you have the latest alpha version?

**Comment by ej8** [comment]
That was the problem. Not sure what version I was on but I updated and everything works now.

Thanks so much!

**Comment by Wolfsblvt** [comment]
Great that it works now (:
