### ISSUE TITLE
Transfer confirm window is messed up

### ISSUE THREAD

**Issue by eralpsahin** [Wolfsblvt/BlossomsPokemonGoManager#26]
The transfer window scales as more pokemons are in the transfer list, but it's size increases too much that confirm button becomes out of reach. I had to rotate my second monitor portrait to be able to click it. Link [here](https://postimg.org/image/clz7qpps7/)

**Comment by Wolfsblvt** [comment]
We'll see if @weblue 's PR fixes it.

**Comment by weblue** [comment]
Fixed
