### ISSUE TITLE
Renaming/Nickname Length

### ISSUE THREAD

**Issue by aja453** [Wolfsblvt/BlossomsPokemonGoManager#264]
I would like to rename in a single batch all Pokemon at once with the Species name and IV rating.  However, many species' nickname length is limited.  I can't figure out the limitation exactly, but those with shorter species names can use %name%%ivrating%, while using this for others with longer names throws off an error because the name is too long after being combined with the full IV rating, specifically the decimal and numbers to the right.  What does work though is renaming the species with longer names by manually typing the species name and the first two integers for the iv rating (86 only vs the 86.66 displayed in the iv rating column).  Is there a way to use %name%%ivrating% and only add the first two integers?  Or maybe display the iv column with only two integers?  Or insert an extra column with only two integers fort he IV rating?  thanks!!

**Comment by Wolfsblvt** [comment]
Yeah, totally :D 
Like everything you are asking for will be part of the next release.
We will add:
- Placeholders for shorter nicknames (Name_4, Name_6, ...)
- Too long nicknames will not throw errors anymore, but cut them off.
- IV rating will only have two character and not more
