### ISSUE TITLE
cannot find javaw in mac os

### ISSUE THREAD

**Issue by foolbear** [Wolfsblvt/BlossomsPokemonGoManager#266]
have already install latest jre.

**Comment by Wolfsblvt** [comment]
Guess you are using the `RunOnUnixLikeSystems.sh` file to start it?

Can you try to open that file with a text editor of your choice and replace "javaw" in there with "java"?
Seems like javaw is not installed on Mac with the JRE.

**Comment by foolbear** [comment]
thanks, it works!

**Comment by Wolfsblvt** [comment]
Easy PR then. Will fix it.

**Comment by Wolfsblvt** [comment]
And fixed.
