### ISSUE TITLE
Go manager 

### ISSUE THREAD

**Issue by mvnipulate** [Wolfsblvt/BlossomsPokemonGoManager#271]
I keep getting this error, it says "need browser" I've asked around and no one else knows what to do

**Comment by Wolfsblvt** [comment]
Please provide the full error message. Best as a Screenshot.

And I guess you use the old version, that error happened there. Download the latest alpha release.

**Comment by Wolfsblvt** [comment]
Can you update here? If there is no response I will close the issue.

**Comment by mvnipulate** [comment]
I have the latest version installed, thid is the error i get.

**Comment by Wolfsblvt** [comment]
I need the full error message. Otherwise I can't help you. I don't know what the problem is.

**Comment by Wolfsblvt** [comment]
I'll close here then.
