### ISSUE TITLE
Column with CP after evolve

### ISSUE THREAD

**Issue by brunoarocha** [Wolfsblvt/BlossomsPokemonGoManager#273]
I guess it would be awesome to see the CP after evolve, to see if my pikachu 65 is better than my raichu 312!

Maybe, the UI is too "messy" with that columns so I think it should be hidden or shown in the menu bar.

**Comment by Wolfsblvt** [comment]
Already added in #262 and will be part of the next version.

Column hiding will be done with the new UI.

**Comment by brunoarocha** [comment]
@Wolfsblvt when is supposed to have a new version?
Nice work btw!! :+1:

**Comment by Wolfsblvt** [comment]
This week (:
Guess very soon.
