### ISSUE TITLE
The risk of using this application

### ISSUE THREAD

**Issue by finalmakerr** [Wolfsblvt/BlossomsPokemonGoManager#275]
Hey friends!
I have a real concern regarding this tool! Now when there have been a permanent ban wave, how safe it's to use it?
Just for example, last week i have done a mass evolve for XP and got about 130-140k which is insane (with lucky egg). Now if u do try that in real-game you may get 60k at max so do you see my point? The evolve part take about 5 sec maybe little more in this tool but in the original game it's take about 30-40sec.

**Comment by Wolfsblvt** [comment]
In the next version there will be a configurable delay between each step of a bulk operation.
That way you can stay save and set it to 30-40 sec for example.

For the risk, I would say the disclaimer explains it quite well. Yeah, you probably violate the ToS with that tool, it's not sure, but I don't think Niantic will hunt after dimple IV users and that use inventory management. It's the bots that are the problem.

But no one knows of course.

**Comment by finalmakerr** [comment]
Ok that's sound promising i guess :) thanks!
