### ISSUE TITLE
Suggestion : Timers

### ISSUE THREAD

**Issue by Bergamof** [Wolfsblvt/BlossomsPokemonGoManager#277]
One of the things that may get people ban are the mass actions (for instance, mass transferring).

Indeed, when you "mass action", PoGoMan begins a new request as soon as the previous has ended. But when you use the app, you need to click, select the pokémon, choose your action, confirm, see the animation (I'm not sure you can pass it), and do all that again.

Then, if they check the requests, they will detect that there are people who did 10 transfers in less than one minute instead of about five.

My suggestion would be to add timers for each action (favoritinng is quicker than transfering for example). When you receive the request response, you launch that timer plus a random number (between 0 and 2 to simulate the fact that we are human ;) ). Then launch the next action, etc.

I think you could make it a parameter, letting people change the value of each timer, and even the range of the random part

**Comment by Wolfsblvt** [comment]
All good suggestions.
So good that they are all implemented already :P
See #157 for the PR.

**Comment by Bergamof** [comment]
Oops, sorry ! Didn't search enough :D 

It's available in the dev release ? I didn't seem to see them :/

**Comment by finalmakerr** [comment]
I started using the dev release but i can't create a jar file using Eclipse as do the following errors:

```
JAR creation failed. See details for additional information.
  Resource is out of sync with the file system: '/PokeGoUtil/console.log'.
  Resource is out of sync with the file system: '/PokeGoUtil/config.json'.
```

and this one with different settings:

```
JAR export finished with warnings. See details for additional information.
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/BlossomsPoGoManager.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/DATA/managers/PokemonBagManager.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/DATA/managers/AccountManager.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/GUI/controller/MainWindowController.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/GUI/controller/ChooseGuiWindowController.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/GUI/controller/LuckyEggGrinderController.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/GUI/controller/LoginController.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/utils/helpers/DateHelper.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/utils/pokemon/PokeHandler.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/windows/MenuBar.java
  Exported with compile warnings: PokeGoUtil/src/me/corriekay/pokegoutil/windows/PokemonTab.java

```

P.S. The application is working using the Run As Java Application though.

**Comment by Wolfsblvt** [comment]
Never worked with Eclipse. So can't help you there, sorry.
