### ISSUE TITLE
Feature request: Evolved CP (Cur)

### ISSUE THREAD

**Issue by gratien-jauffret** [Wolfsblvt/BlossomsPokemonGoManager#278]
Hey guys,

nice tool indeed, thanks for your work :)
Would you mind adding the eponymous column please ?
I know you can get that info anywhere but it would be nice to have it in the table next to everything else.

**Comment by Wolfsblvt** [comment]
I don't understand what that column would mean.
"CP Evolved" displays the exact CP after the evolve, without any power-up.
The column "Max Evolved CP (Cur)" displays the maximum CP the Pokémon can have when evolved and fully powered up at your current level.

I guess that's what you mean? We have that already.
