### ISSUE TITLE
Risk get ban?

### ISSUE THREAD

**Issue by edmondhk** [Wolfsblvt/BlossomsPokemonGoManager#281]
I know always have a risk, but how risky?
Does the program use any extra API/read anything not being used by the game itself?

**Comment by Wolfsblvt** [comment]
The question has been asked several times before.
Guess the disclaimer explains it quite well. There is a risk, sure, but we would say not that high.
We do not use any pokémon catching or pokéstop turning things bots use. We mimic the same calls the game does to acquire the data and do bulk operations.

With the next version there will be random delays between each bulk step that you can even configure to like 30-40 seconds between evolves if you want.
