### ISSUE TITLE
Add a column catch date

### ISSUE THREAD

**Issue by BHMath** [Wolfsblvt/BlossomsPokemonGoManager#282]
Is it possible to add a column with the catch date in order to sort pokemon from the newest to the oldest ?

**Comment by Wolfsblvt** [comment]
It's even part of the beta release :D
You haven't downloaded the latest version for a while, right? :P

**Comment by BHMath** [comment]
Oh sry I did try yesterday but couldn't find the column. My bad

**Comment by BHMath** [comment]
this is weird bcause I can't find this column see

![image](https://cloud.githubusercontent.com/assets/6143089/17777572/4e4d84c2-6561-11e6-96b8-7306397d828f.png)

**Comment by Wolfsblvt** [comment]
It's in the latest alpha. I was mistaken.

**Comment by BHMath** [comment]
Hmm ok the alpha version is newer than beta my mistake. Thanks !

**Comment by Wolfsblvt** [comment]
Yeah :D
We will think about a better way to handle new releases in the future :P
