### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by GreatApo** [Wolfsblvt/BlossomsPokemonGoManager#284]
Today i can't log in at all... no errors no nothing. After inputing username+password and press to connect it just does not open again.

**Comment by Wolfsblvt** [comment]
Which version do you use? Are you using the latest alpha?
Is your game still working on your smartphone (eg catching Pokémon and spinning stops)?

**Comment by GreatApo** [comment]
I was using an old version and I tested the new one... None works, both for me and one of my friends. The account works...

I thought there was an update or sth. Works for you?

Nice work by the way.

**Comment by Wolfsblvt** [comment]
The new alpha version has fixed some bugs with login and stuff.
Keep an eye on hidden windows behind other open windows. The app tends to open behind everything else, sadly xD

Otherwise, with the new alpha you should not get errors.
Can you try executing the jar file via console and look if there are errors written? Or check if there is a console.log file in you directory.

**Comment by GreatApo** [comment]
The account seems to got banned. I thought it was working because i was able to log in from Pokeclub site but i faced problems with https://pogobag.me/ too. After using an other account i was able to log in.

 Sorry for the false alarm :/
Here is the log, maybe you could throw a message like the one on pogobag ("There was an error when requesting your data (This could be because your account is banned or Niantic's servers are busy). Please try again.").

 [08/18 21:41:49]: D/RequestHandler: Authenticated with static token
[08/18 21:41:52]: Successfully logged in. Welcome, ACCOUNTNAME.
[08/18 21:41:52]: Exception in thread "main" [08/18 21:41:52]: java.lang.NullPointerException
[08/18 21:41:52]:   at me.corriekay.pokegoutil.windows.PokemonGoMainWindow.<init>(PokemonGoMainWindow.java:31)
[08/18 21:41:52]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.logOn(BlossomsPoGoManager.java:220)
[08/18 21:41:52]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:50)

Again nice work.

**Comment by Wolfsblvt** [comment]
It's difficult to regocnize in-code when people are banned. Niantic has several kinds of bans and that is quite complicated.

But thanks for clearing that up here (:
