### ISSUE TITLE
Right align numbers

### ISSUE THREAD

**Issue by ritsu** [Wolfsblvt/BlossomsPokemonGoManager#291]
What do you guys think of right aligning numbers in columns that contain numbers? I find it easier to quickly scan and compare long lists of numbers when they're right aligned.

```
8
372
13
7965
158
```

vs

```
   8
 372
  13
7965
 158
```

For floats, we'd have to format to a fixed number of decimal places for right aligning to make sense.

If you're close to the JavaFX release, this might be something to consider for the new GUI? Thanks!

**Comment by Wolfsblvt** [comment]
Will be in for the new UI, but good idea!
