### ISSUE TITLE
Columns not saving after refreshing pokemon list.

### ISSUE THREAD

**Issue by heIlo** [Wolfsblvt/BlossomsPokemonGoManager#292]
Please check the added functionality for alpha2. It doesn't seem to be working for me when i try to sort my duel ability to the front and press refresh list?

**Comment by QuadTog** [comment]
Specifically you're talking about re-arranged columns not remembering their position/order right?

Or do you mean once columns are sorted they forget their sort on refresh?

**Comment by heIlo** [comment]
oh, i'm sorry. i guess i misread. yes, i meant the former. could that be a new feature please?

**Comment by QuadTog** [comment]
We'll look into it. Currently there is work on a new interface so this issue could resolve itself shortly.

**Comment by Wolfsblvt** [comment]
There is still an issue open for that: #65
It includes all, and will be done with the new UI. The sorting was an easy fix, column ordering is more difficult, so guess that have to wait more.
