### ISSUE TITLE
Console UTF8 output

### ISSUE THREAD

**Issue by kkleejoe** [Wolfsblvt/BlossomsPokemonGoManager#293]
1. add static function in me.corriekay.pokegoutil.utils -> Console.java :
   public static void setDefaultCharset(final String p_charset) {
     try {
       final Field charset = Charset.class.getDeclaredField("defaultCharset") ;
       charset.setAccessible(true) ;
       charset.set(null, Charset.forName(p_charset)) ;
     } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
       ex.printStackTrace() ;
     }
   }
2. add function call in Console constructor :
   setDefaultCharset("UTF8") ;

**Comment by Wolfsblvt** [comment]
Can you explain why this is needed?

**Comment by kkleejoe** [comment]
if rename pokemon in Japanese or Chinese, the console would output ??? ???? ..........
if change the default charset to UTF8, the output log will display correctly.
Thanks.

**Comment by Wolfsblvt** [comment]
okidoki, will be added then.

**Comment by Wolfsblvt** [comment]
That's not working. I just breaks the console output even for the "é" in Pokémon. Japanese signs are just question marks.

Have to check more there, or you have to correct your code.

**Comment by kkleejoe** [comment]
it's working for me now .

## in me.corriekay.pokegoutil.utils.ui.Console.java

```
public Console(String windowName, int x, int y, boolean smartscroll) {
    .
    .
    setDefaultCharset("UTF8") ;

    ConsolePrintStream cps = new ConsolePrintStream();
    System.setOut(cps);
    System.setErr(cps);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}

public static void setDefaultCharset(final String p_charset) {
  try {
    final java.lang.reflect.Field charset = java.nio.charset.Charset.class.getDeclaredField("defaultCharset") ;
    charset.setAccessible(true) ;
    charset.set(null, java.nio.charset.Charset.forName(p_charset)) ;
  } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
    ex.printStackTrace() ;
  }
}
```

---

**Comment by Wolfsblvt** [comment]
True! That really works. Will made a pull request.
