### ISSUE TITLE
IV% column shows XX instead of 100%

### ISSUE THREAD

**Issue by Macrike** [Wolfsblvt/BlossomsPokemonGoManager#294]
**Version:** 0.1.2-alpha.2

I have one Pokemon with 100% IV. In v0.1.2-alpha.1 the value in the IV% column appeared as 100% but in v0.1.2-alpha.2 the value appears as XX.

<img width="369" alt="screen shot 2016-08-19 at 06 58 30" src="https://cloud.githubusercontent.com/assets/1828696/17800346/6b41fd46-65da-11e6-9d10-b3781d9b43a8.png">

**Comment by Wolfsblvt** [comment]
Yes, that's intended behavior. For the replace patterns for renaming it was needed to reduce the values to two characters. That way we had to find a solution for 100%, which has three. We came up with using "XX" as the perfect value.

For consistency we use this replacement in the column too.
