### ISSUE TITLE
Fields for evolution not visible

### ISSUE THREAD

**Issue by QuAzI** [Wolfsblvt/BlossomsPokemonGoManager#297]
"Candied", "To Evolve" and "Evolvable" must be near and visible after startup (as before) - please make it closer to first column instead MAX CP at 40 lvl (too unattainable level)

**Comment by Wolfsblvt** [comment]
Columns sorting will be saveable in the future, you can even hide unneeded columns and some will be hidden by default.
See issue #65 for that.

When that is implement we will re-think the default order of columns too.
