### ISSUE TITLE
Project 'PokeGoUtil' is missing required Java project: 'Corries Util Library v2'

### ISSUE THREAD

**Issue by SuigetsuSake** [Wolfsblvt/BlossomsPokemonGoManager#3]
Trying to compile the project in Mac and got this error, can we download the missing project somewhere ?

PS : I also had an issue with Apache commons lang which was referred as an absolute path, i added org.apache.commons.commons-lang3 as a maven dependency for now

**Comment by sbell8-chwy** [comment]
Same. I added the lang3 dependency and the org.json dependency. I would be nice to be able to build and run this locally so we could help out.

**Comment by ghost** [comment]
Hey, just a heads up, I've merged the tools from that project into the actual repository, so you should be able to get it up and running now!

**Comment by sbell8-chwy** [comment]
Just pulled in latest and it builds for me. Thanks.
