### ISSUE TITLE
Quick and Dirty Fix for Time Delay Between Actions

### ISSUE THREAD

**Issue by OverlordPhaethon** [Wolfsblvt/BlossomsPokemonGoManager#300]
This is an extremely dirty workaround for those worried about getting banned because of unusually fast client actions. I didn't feel like spending more than 20 seconds on this, as I'm sure the next release or commit will be much more succinct and expert than whatever I could come up with. Despite the min and max millisecond random integer delay built in, I prefer to have 30 seconds between actions to stay on the safe side. For the developer branch, inside your IDE, if you open source packages, expand me.corriekay.pokegoutil.utils, and then open Utilities.java, you can navigate to line 65 and replace with `System.out.println("Waiting 30 seconds.");` and replace line 66 with `TimeUnit.MILLISECONDS.sleep(30000);`

There will be a message at the bottom of your manager that says: "Could not fetch config item 'whatever'! Fallback to default" This shouldn't effect any of the actions, and you will notice that between each transfer/rename/whatever, that there is a 30 second delay. I've tested this on my own account of course, and ran into no issues.

Sorry to the devs if this is improperly placed, but I figured it'd lower the number of issues on 'time delay', and alleviate some users fears of having Niantic target them with a ban until there is a better solution. Thanks for all your hard work, can't wait to see what the next commits have in store for us!

**Comment by Wolfsblvt** [comment]
Guess that should work, yes. But not everyone is capable of using the dev version with an IDE :D 
For others, the solution would be to set the delay manually in the config.json to over 30 seconds.
If you don't want to evolve two or more Pokémon so that the settings get added automatically, you can add them manually there.
This should be the code for delay on evolve. Replace your delay entry, if it doesn't exist add it add the highest level. Take care for json formatting rules. Comma at the end of each block, etc.

``` json
    "delay": {"evolve": {
        "min": 1000,
        "max": 5000
    }}
```

**Comment by cmhamm** [comment]
Just a small suggestion: Perhaps set the default values to something "safer." I didn't know the configuration syntax, so I had to evolve, transfer, rename and favorite one time each, just so the config file would be filled out and I could alter it. (I still don't know the correct value for powering up,  as I don't have enough Stardust to power up two characters.) There's really no "legitimate" way to evolve two Pokémon in 1-5 seconds, so unless you know the syntax ahead of time, you'll need to make at least one "fishy" evolution to write the default values to the config.

At any rate, if the default values are 30000-35000, the first actions won't be "dangerous," and people will be able to tailor them to their own comfort levels.

EDIT: I'm also aware that Niantic can surely detect the use of the application, even if the values are set to "safe" ones. However, I'm a purist, and really don't want to do anything "unfair." I just don't have the patience to poke around on my phone for hours on end, renaming each character by hand...

**Comment by OverlordPhaethon** [comment]
I had just upgraded to the latest dev and didn't see the delay settings in config, didn't even think to try the transfer once and recheck for the syntax.  Don't be ghetto like me and edit your Utilities file! Thanks for the info Wolfsblvt.
