### ISSUE TITLE
Add a leftmost number column

### ISSUE THREAD

**Issue by cmhamm** [Wolfsblvt/BlossomsPokemonGoManager#302]
I want to start off by thanking the community behind this and other like-minded projects. You time is very much appreciated.

A very small request. Sometimes, I want to do something to the "top x" number of Pokémon. It would be nice if a simple left-hand column can always be sequentially numbered, regardless of sorting. For example, if I wanted to rename my top 25 IV%, I could sort by that column, and select the top 25. Then I could sort by CP, and see my top 40 CP, etc. My coding skills are dangerous at best, or I would happily contribute. At any rate, I suspect something like this would not be difficult to add, and would save me a lot of line counting. :-)

Thanks again for everyone's contributions.

**Comment by Wolfsblvt** [comment]
Yeah, guess that's possible.

**Comment by Munkenmo** [comment]
Was just about to request this before I noticed it here. A number column would be a great time saver when I'm working out just how many pidgeys I need to mass transfer.
