### ISSUE TITLE
Typing 2 shows "No", same as Normal when Pokemon don't have a second typing

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#305]
Hola!

Example: Arcanine whos only fire, when using the renaming convention_short Type1 Type2, will show FiNo, instead of just Fi.

Suggestion; pokemon with only single types, that encounter a rename string Type1 Type2 should show empty instead of "no".

**Comment by Wolfsblvt** [comment]
Yeah true, that's a bug.
I won't add empty string though. Many people depend the renaming feature on exact string length and know that Type2 is at characters 8-10 and so on. Maybe I'll just go with Underscores or something like that.

**Comment by Wolfsblvt** [comment]
Fixed, PR got merged.
We go with the Underscores "__" for no second type for now.
