### ISSUE TITLE
Run alpha1 perfect, but alpha2 with main class Error

### ISSUE THREAD

**Issue by aziechang** [Wolfsblvt/BlossomsPokemonGoManager#306]
First I would like to thank you all for this superb tool, it's by far my favorite tool and is getting better everyday.

I've been using it perfectly since early 0.1.1, 0.1.2 alpha.1, but I just updated to 0.1.2 alpha.2, it gave me
 Error: Could not find or load main class me.corriekay.pokegoutil.BlossomsPoGoManager

I am running Java(TM) SE Runtime Environment (build 1.8.0_101-b13), so I think I've met the requirement?

Could you please help on this? Now I can only use old 0.1.2 alpha.1.

Thank you.

**Comment by aziechang** [comment]
OS is Ubuntu 14.04, running on ARM cpu, just in case information needed. Thank you.

**Comment by deadthoma5** [comment]
I had this issue in Fedora 23 x64 until I switched from openjdk to oracle jdk.

BPGM 0.1.2.alpha.2 works for me now

**Comment by Wolfsblvt** [comment]
Do you run the jar file directly? Or do you use the shell script?
If second, try running the jar directly via command line: `java -jar BlossomsPogoManager.jar`

**Comment by aziechang** [comment]
Hello,

   Thanx for the help.

   I had other issues with openjdk on earlier versions of BlossomsManager,
so I switched for oracle JDK 8 already.

   Also, I am running with command line, sudo java -jar
BlossomsPogoManager.jar.

   I don't know where went wrong, but I just use alpha1 now since it's
pretty good already.

   Tried using alpha2 on windows computer, it works fine.

Andrew

**Comment by GuillaumeCisco** [comment]
Just used Oracle JDK instead of Open JDK and it worked ;)
Thanks to http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/#

**Comment by thisischrys** [comment]
In case anyone runs into this in the future:
I have no problems running this in openjdk 1.8.0_121
