### ISSUE TITLE
Transfer After Evolve

### ISSUE THREAD

**Issue by OverlordPhaethon** [Wolfsblvt/BlossomsPokemonGoManager#307]
New developer build is working great, using it for a 12 candy pokemon grinder and noticed that if the option in settings "Transfer After Evolve" is selected (highly useful if you need candies mid batch evolve), there is no delay between evolving and transferring. I'm sure it's a minor fix, but important in terms of imitating actual client operation. The delay specified for transfer should also act in this instance. Otherwise, I'm very pleased with the project so far, keep up the good work!

**Comment by Wolfsblvt** [comment]
Yeah, you are right. Will be fixed.

**Comment by Wolfsblvt** [comment]
Fixed, PR got merged.
