### ISSUE TITLE
%level% to be 2 digits

### ISSUE THREAD

**Issue by alexcan97** [Wolfsblvt/BlossomsPokemonGoManager#308]
The rename function works great
especially the new update has the %name% length option.
but for %level%, it's better to have the option to choose or set it as 2 digits like xx instead of xx.0
cause for most pokemons, the level is xx.0 
this is not a big deal, just would be nice if it get fixed in next update.

**Comment by Wolfsblvt** [comment]
Fixed? The level is always a double with `.0` or `.5`. If you've powered up a pokemon, it is very likely that it is a `.5`.
Closing here then.
