### ISSUE TITLE
suggestion: log Pokemon that are transferred

### ISSUE THREAD

**Issue by dotheknifefight** [Wolfsblvt/BlossomsPokemonGoManager#314]
It would be cool if the manager would log which Pokemon you have and which you have transferred. Then you can look at the logs and see what you've caught and the trend in their stats and whatnot. Also, is there a way to display whether a Pokemon is caught or hatched?

**Comment by Wolfsblvt** [comment]
> It would be cool if the manager would log which Pokemon you have and which you have transferred. Then you can look at the logs and see what you've caught and the trend in their stats and whatnot.

That would mean you could only see transferred Pokémon that you have transferred with this tool, and only at the system where you transferred it. Don't think that would really help with anything? :D 

> Also, is there a way to display whether a Pokemon is caught or hatched?

No. There is no chance to acquire that information.
