### ISSUE TITLE
What is Alternative IV calculation (Weighted Stats)

### ISSUE THREAD

**Issue by a95patel** [Wolfsblvt/BlossomsPokemonGoManager#316]
Hey, great work on the program. 

I was looking over the latest update today and I was wondering what is Alternative IV calculation (Weighted Stats)? 

If tried searching the issues list and comments for additional information but I had no luck finding it. If you can point me to the right area where I can find this information would be happy to read through it and understand it. 

Thanks

**Comment by Wolfsblvt** [comment]
Hey. Good question, and you are right, we do not explain it in the tool right now. That's cause the old UI is a bit clunky and we try to focus adding features to the new one.

I guess the best explanation what it means can be found in the original issue: #165 
The second comment by OP even gives a reallife example which shows the advantage/difference of this calculation.

**Comment by a95patel** [comment]
That's fine. Thank you for linking the original issue. I had read the issue last week but I couldn't find it when I was searching for it yesterday late last night. 

The example provided makes sense to me. And I guess looking and doing compares between both IV's for my own pokemon's  will help me understand it more. 

I guess for now I will have to just toggle it on and off and copy the 2 different IV's into excel to see the differences.
