### ISSUE TITLE
Prevent transfer of favorited pokemon when in "transfer after evolve" is selected

### ISSUE THREAD

**Issue by akemi12** [Wolfsblvt/BlossomsPokemonGoManager#318]
Is it possible to prevent transferring favorite pokemon when "transfer after evolve" is selected like how it is prevented for individul pokemon? I forgot I had it selected for my pidgies when I wanted to fit a few in at the end of a lucky egg in the last minute... It would be nice to safeguard against doing things like that... I did it with my gyarados which I was not too happy about obviously

**Comment by ritsu** [comment]
Submitted PR for this https://github.com/Wolfsblvt/BlossomsPokemonGoManager/pull/319

**Comment by Wolfsblvt** [comment]
Fixed with #319.
