### ISSUE TITLE
Suggestion: Player info tab

### ISSUE THREAD

**Issue by weblue** [Wolfsblvt/BlossomsPokemonGoManager#32]
Creating a player info tab with the information from the console that refreshes after an action and a lucky egg button/counter. Thoughts?

**Comment by Wolfsblvt** [comment]
Have you tried clicking `File -> View Trainer Stats`?

**Comment by Wolfsblvt** [comment]
PlayerInfo is displayed like I said, Lucky Egg timer is suggested in #5, so I'll close here I guess.
