### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ghost** [Wolfsblvt/BlossomsPokemonGoManager#33]
Hey all, I created a discord channel so that we can discuss things in a live setting. :)
https://discord.gg/UpU9W

**Comment by andrewmcwatters** [comment]
dank memes

**Comment by Wolfsblvt** [comment]
Open till the readme is there, then I'll close this issue.

**Comment by eralpsahin** [comment]
Invite is invalid now, do we still have discord channel? @Ljaysoft

**Comment by Ljaysoft** [comment]
yes, the invites only work for a day, here's a new one https://discord.gg/efzwE

**Comment by weblue** [comment]
Added a Readme with a permanent invite link
