### ISSUE TITLE
Error: Unable to access jarfile BlossomsPogoManger.jar

### ISSUE THREAD

**Issue by chaseb9** [Wolfsblvt/BlossomsPokemonGoManager#332]
When I open RunOnWindows.bat it give me the error message of Error: Unable to access jarfile BlossomsPogoManger.jar  https://gyazo.com/4ccb9f5ef504e771286c0089849d5d9d

**Comment by Wolfsblvt** [comment]
Yeah, cause there is no `BlossomsPogoManger.jar` in the prep folder. It's for preparation for the final release :P
If you use the github source, you have to compile and start on your own, for example with an IDE of your choice.
