### ISSUE TITLE
Capitalize STAB in when renaming by move1/2

### ISSUE THREAD

**Issue by Angelarius** [Wolfsblvt/BlossomsPokemonGoManager#339]
It would be nice when renaming Pokemon by their move types to have STAB capitalized and non stab in lower case. For example I manually renamed my 93% Vileplume with razor leaf and solar beam to GRA-GRA 93 and my 89% Dragonite with dragon breath and hyper beam is named DRA-nor 89. Thanks for reading.

**Comment by Wolfsblvt** [comment]
Actually a cool idea and shouldn't be that difficult.
