### ISSUE TITLE
User-defined Panel

### ISSUE THREAD

**Issue by Pokem0n2** [Wolfsblvt/BlossomsPokemonGoManager#341]
i hope it can remember last time columns' position and size, otherwise u need to move the columns and resize em after refreshing the form. BTW, a panel property .xml maybe a not bad solution. look forward to ur endeavor! :+1:

**Comment by Wolfsblvt** [comment]
With the next version, column ordering will stay the same if refreshed and after operations.
The sorting is already saved even when re-opening the app.

All other is planned for the new UI, with #65.

**Comment by Pokem0n2** [comment]
that's absolutely an exciting notification, it will be a qualitative leap compared with the old version! Wait in Hope!
