### ISSUE TITLE
IV % displayed as XX if it is 100

### ISSUE THREAD

**Issue by nts64** [Wolfsblvt/BlossomsPokemonGoManager#342]
Used to display correctly before, when exact values were shown. Started showing as XX when the rounding was introduced.

**Comment by Cryptically** [comment]
IV 100% is intended to be displayed as XX.

**Comment by Wolfsblvt** [comment]
Yep, that's intended behavior. We had to change 100% to something with only two characters for the renaming patterns, and thought that it would be more consistent to use it in the table too then.
