### ISSUE TITLE
What device_info gets send with every request?

### ISSUE THREAD

**Issue by subzerofun** [Wolfsblvt/BlossomsPokemonGoManager#353]
Beforehand - muchas gracias for your tool!

Why i ask this: My first account got banned because i have used too much 3rd party tools (everything from automated transferring/evolving, botting – idiotic, i know...).
So with my new account i haven´t touched any 3rd party tools yet, only played via the game client.
But i would really like to use your tool to speed up my leveling progress without getting hit by the next banwave. I know you can´t guarantee that using your manager is 100% "ban-safe" (but maybe 99%? 😊).

My question: If i usually play with an iPhone 6s, log out of the game and start up your tool on my desktop and use it to transfer/evolve pokemon (from the same IP address to be safe) – what device_info do the Niantic Servers get?

The device_info values were ignored by a lot of map scanner projects (always sending the same hardcoded Android values for every map request...) and that made it almost too easy for Niantic to detect. They just had to compare the hardcoded device_info that was sent via the pgoApi, the location of requests, IP address (before proxy support came out) and the session times. If too much accounts had similar values they got flagged for a ban (i know that this is just pure speculation).

**Comment by Wolfsblvt** [comment]
Guess you have to look deeper into the PokeGo-API by Grover which we use here.
That's where such stuff is defined.
