### ISSUE TITLE
Returning wrong number of pokemons

### ISSUE THREAD

**Issue by Cryptically** [Wolfsblvt/BlossomsPokemonGoManager#355]
PokemonGo.getInventories().getPokebank().getPokemons() isn't returning the correct number of pokemons.

In the actual pokemon go app, it shows I've 250 pokemons, but the api call only returns 241.

**Comment by GramThanos** [comment]
You have 9 eggs. 241+9 = 250

**Comment by Cryptically** [comment]
Oh wow, those eggs also count into the Pokemon inventory. Didn't know that at all.

**Comment by Wolfsblvt** [comment]
Yeah, the app even shows the (+x Eggs) in the console output box for that reason, so that players understand the difference in those numbers :P
