### ISSUE TITLE
"Caught With" column is wrong for hatched pokemon

### ISSUE THREAD

**Issue by FernandoTBarros** [Wolfsblvt/BlossomsPokemonGoManager#364]
If a pokemon is obtained by egg hatching, this column should show a correct label instead of "Poke Ball".
Perhaps "Egg Hatched". 
I tried but can't find an option on the pokemon go api to know if a pokemon is hatched or not.

**Comment by Wolfsblvt** [comment]
Duplicate of #129.
Same as there, we can't fix it as long as the PokeGo-API doesn't send any info about this.
