### ISSUE TITLE
Evolution Calculator

### ISSUE THREAD

**Issue by schawsk** [Wolfsblvt/BlossomsPokemonGoManager#372]
We already have a two max evolved tabs (current and 40). However what would be nice is to see the exact CP a pokemon would evolve into without any powering up. I often find myself using an external website for such calculations (I use this manager solely to quickly check exact IVs of Pokemon) That would help massively. Cheers!

**Comment by Wolfsblvt** [comment]
It is already included. Do you use the latest version, `v0.1.2-alpha.2`?

**Comment by schawsk** [comment]
really? cool, no i used the v0.1.2-alpha.1
