### ISSUE TITLE
Feature request: Save column order

### ISSUE THREAD

**Issue by schawsk** [Wolfsblvt/BlossomsPokemonGoManager#373]
Since I use this tool Mostly to see my IVs and what the CP of the pokemon will be after evolution, I would like to see those columns frst. When I drag them to the left, and then use the search bar, the column order resets everytime. It would be a huge help if this tool would remember my custom column order, if possible even across sessions!
Cheers!
PS: (regarding the preious issue) Yes i updated to the newest release now :)

**Comment by Wolfsblvt** [comment]
Column order is saved during the session with the latest release.
For saving across sessions, there is an issue open #65, and it will be implemented with the new UI (:

**Comment by matijarma** [comment]
hey Wolfsblvt, first of all thanks so much for this fantastic tool and all the effort you put in, really means a lot!
secondly, i'd just like to strongly add to this request, as the column order not being saved is a real pain in the ass, i'll try to illustrate very shortly: type, attack, level etc don't mean nothing to me, and they take huge amount of space. i do however need the FAV column all the time, and its all the way at the end. what i also always need as a priority is the candy column, and i need to be able to see it clearly and at once, which is not possible while it is crammed between other numbers. so i have to re-arrange and widen/tighten the columns. MAX CP, MAX CP EVOLVED, hugely needed - the (40) variations of those columns are for me USELESS.

so with this very brief story you can imagine how frustrating it is to go trough the process every time :)
looking forward to the update as i hatched my first gen2 eggs today, keep up the good work and possibly allow us to save the column order as well soon, thanks :)
