### ISSUE TITLE
Characters error for french translated pokemon species

### ISSUE THREAD

**Issue by GeoBSI** [Wolfsblvt/BlossomsPokemonGoManager#379]
Hi, there seems to be some character encoding problems, particularly with french accents (see screenshot below). 

It only appears with pokemon species names, there's no problem when I rename them (the french accents appears correctly on the nickname). The male / female character for nidoran also appears correctly.
I guess it comes from the imported translation of the pokemon species. I see this problem only with the french language.

It wasn't happening on last alpha, but appeared with recents developer builds.

![capture d ecran 2016-09-15 20 06 07](https://cloud.githubusercontent.com/assets/21092086/18561854/dab121d6-7b81-11e6-84bc-4399f43c349f.png)

**Comment by Wolfsblvt** [comment]
Fixed with linked PR.
