### ISSUE TITLE
Fairy, Ice, and Fighting Unicode not registering with Pokemon Go

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#380]
Using %type_1_uni%%type_2_uni%|%move_type_1_uni%%move_type_2_uni% %iv_rating%|%level%. Everyone else is pretty okay. 

Screens below. Should be expecting a Fighting, Ice, or Fairy, and get blanks.

![screenshot_20160915-132859](https://cloud.githubusercontent.com/assets/13637696/18568805/d4f613f6-7b53-11e6-9c93-372066ab163e.png)
![screenshot_20160915-132918](https://cloud.githubusercontent.com/assets/13637696/18568804/d4f61cca-7b53-11e6-8f26-0fe269c54320.png)
![screenshot_20160915-133003](https://cloud.githubusercontent.com/assets/13637696/18568806/d4f9cab4-7b53-11e6-84ec-1ad4cae134ea.png)

**Comment by potatoboy** [comment]
I'm having a similar issue but with different characters.
I renamed some using the same pattern to illustrate.
![content- 2f 2fcom google android apps gsa velvet extradex extradexhostprovider 2fassist com google android apps gsa assist screenshotprovider 2fcom google android apps gsa assist screenshotprovider 2fscreenassistscreenshots 2fscree](https://cloud.githubusercontent.com/assets/607393/18617329/16ec0268-7d9b-11e6-9353-b6c3229669fd.png)

**Comment by FernandoTBarros** [comment]
Yes, unfortunally the Unicode characteres doesn't work for everyone the same way.
Do you guys managed to rename manually using unicode and get working? If so, please tell what character has worked, and then we can think of some configuration.

**Comment by Wolfsblvt** [comment]
Unicode stuff moved to **v0.1.4**.

**Comment by Wolfsblvt** [comment]
We can't provide working unicodes for every phone type. That's why we will make unicodes customizable in the future.
See #301 for this.

Closing this here now.
