### ISSUE TITLE
Feature Request: Evolvable After Transfer+

### ISSUE THREAD

**Issue by Chazn2** [Wolfsblvt/BlossomsPokemonGoManager#386]
I would rather like if the 'number evolvable' column had an option (check-box in options?) that allowed the number to show how many you can evolve if you also transfer them.

On this note, but slightly harder to implement would be an 'evolve maximum possible' - button. So it'd first transfer the amount selected that it needs to evolve the most - depending on if you have transfer after selected or not, it'll then evolve everything it can so that no maths is needed.

**Comment by Wolfsblvt** [comment]
Have you checked it? It does already :P
Just check the "Transfer after Evolve" option under the settings, than they will be automatically transferred, and the "Evolvable column" takes the additional candy in mind.

Edit: You have to refresh your list after checking that option right now though. That will be fixed soon.
