### ISSUE TITLE
Pokemon with no second type get type 'No' using %type_2% when renaming

### ISSUE THREAD

**Issue by syrusgreycloak** [Wolfsblvt/BlossomsPokemonGoManager#389]
Version 1.2

While not a major issue, this could lead to confusion as users may forget and assume they should be receiving STAB (even though you now capitalize the moveset type) if the Pokemon possesses a Normal type move.

My suggestion would be to have %type_2% either return two blank spaces, two x's (xx), or the %type_1% result.

**Comment by Wolfsblvt** [comment]
Can you provide a screenshot?
It should already been fixed that "None" gets translated to `__` for pattern replace.

**Comment by ISeeTanamon** [comment]
confirmed its fixed for me:

![capture](https://cloud.githubusercontent.com/assets/13637696/18597597/8bef389e-7c03-11e6-9777-7a4209441f23.PNG)

**Comment by Wolfsblvt** [comment]
Kk, then close here.

**Comment by syrusgreycloak** [comment]
Downloaded v0.1.2 binary today.  Does not put in '__'.  Attached screenshot.  Perhaps it's fixed in dev version. I can try that.

![pgomgr_screencap](https://cloud.githubusercontent.com/assets/11563803/18600392/5bcf5bc6-7c2b-11e6-8026-00124b0a11b3.PNG)

**Comment by Wolfsblvt** [comment]
If you can try that would be cool. I don't understand why this doesn't work :-/

**Comment by syrusgreycloak** [comment]
My best guess is that it was a java cache issue as it seems to have resolved itself and I'm now getting the capitalized move types for STAB.
