### ISSUE TITLE
Inconsistent Capitalization for Typing

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#391]
Attached. Some is 

[Cap/low][Cap/low] < Preferred
[low/low] < meh
[Cap/Cap] < meh

Patterns used:

%type_1%%type_2%%iv_rating%%move_type_1%%move_type_2%%level% 
⛨ %iv_rating%%move_type_1%%move_type_2%%level%

![1](https://cloud.githubusercontent.com/assets/13637696/18597726/19f22e1c-7c04-11e6-8c88-75b5f7e72bf7.PNG)

**Comment by Wolfsblvt** [comment]
Move types are capitalized when STAB applies, and not when it doesn't.
So what's the error here? I don't really see it.

**Comment by ISeeTanamon** [comment]
Oh, I didnt know that was a feature. I wholeheartedly remember it was all Cap/Low when we did move and typing.

Please close.
