### ISSUE TITLE
Renaming Not Matching Pattern

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#393]
Dragonite with Steel Wing and Dragon Claw should be StDr. Its showing as StSt.

Pattern used: ⛨%type_1%|%iv_rating%%move_type_1%%move_type_2%%level%

SS: 
![3](https://cloud.githubusercontent.com/assets/13637696/18597894/0162829c-7c05-11e6-9394-0f64f8d06dff.PNG)

**Comment by Wolfsblvt** [comment]
Fixed already with #388.
Will be part of the next version.
