### ISSUE TITLE
Location Question

### ISSUE THREAD

**Issue by daniel3428** [Wolfsblvt/BlossomsPokemonGoManager#398]
I used another Pokemon management tool.
It let me set my starting location.
I think setting the location nearby where I logged in last time can avoid to be banned.
BlossomsPokemonGoManager does not need to set the starting location.
What is the default starting location.
Thanks.

**Comment by Ryanizleee** [comment]
Yes I am also curious about this as well.

**Comment by Wolfsblvt** [comment]
The location is never set. That means "GPS not found" is likely wha the API gets from us.
That makes the tool even safer, cause you don't have a static location.

**Comment by daniel3428** [comment]
Thanks. This is awesome setting.
