### ISSUE TITLE
Font-Size does not work

### ISSUE THREAD

**Issue by Ryanizleee** [Wolfsblvt/BlossomsPokemonGoManager#399]
Seems like the font resizing feature isn't working, but language changing works.
Also, a max power up function would  be nice, or an option to input x times to power up.

**Comment by Wolfsblvt** [comment]
What does "not working" mean?

Yes, is planned with #59.

**Comment by Ryanizleee** [comment]
Not working as in the size of the font isn't changing when adjusted to another size.
