### ISSUE TITLE
Pls hotfix this: %move_type_2% ALWAYS refers to %move_type_1%

### ISSUE THREAD

**Issue by DrDragonKiller** [Wolfsblvt/BlossomsPokemonGoManager#400]
Yeah pretty simple
you have a pokemon with a **normal** quick attack and a **flight** charge attack
than you use "_%move_type_1% & %move_type_**2**%_" to rename it
the new name is "_NO & **NO**_" (if stab applies otherwise lowercase)

would be cool if you do a hatfox for it and update the current version <3

**Comment by Wolfsblvt** [comment]
This is fixed with #388. Will be part of the next version.
We'll see, maybe not a Hotfix, but won't take another month till the next update now :P
