### ISSUE TITLE
"Evolvable" rounded incorrectly

### ISSUE THREAD

**Issue by DrDragonKiller** [Wolfsblvt/BlossomsPokemonGoManager#401]
![wrong calculation](https://cloud.githubusercontent.com/assets/17345712/18618617/d51e85a4-7dea-11e6-9f3d-7a483025420b.PNG)
(Rattfratz = Rattata)
299 / 25 =/= 12
and no I didn't check transfer after evolve (if that's even change the calculaton?)

**Comment by FernandoTBarros** [comment]
After each evolve you gain a candy. So in fact it's 299+11 (possible evolutions) / 25 = 12
