### ISSUE TITLE
GUI looks strange in HiDPI mode

### ISSUE THREAD

**Issue by robinduckett** [Wolfsblvt/BlossomsPokemonGoManager#404]
![See screenshot here](https://cloud.githubusercontent.com/assets/17959/18620095/d854a1d6-7e03-11e6-909f-2f34ca50ce7d.png)

**Comment by Wolfsblvt** [comment]
You can reduce the font-size a bit more. If it isn't low enough, try to set it even lower in the config.json.
But for now, guess we can't fix it with the old clunky GUI.

Tell me if that works.
