### ISSUE TITLE
[1.2] Charset mismatch 

### ISSUE THREAD

**Issue by sholan** [Wolfsblvt/BlossomsPokemonGoManager#406]
Hello dear Dev,

Since 1.2 (not present in 1.2-alpha), there is an issue with charset encoding :
![image](https://cloud.githubusercontent.com/assets/6232311/18626195/be5d0c28-7e53-11e6-9788-157d2c6f7ae1.png)

Looks like the dictionnary used to translate English species name to french species name is not using the correct charset.

Regards, thanks for your work.

**Comment by Wolfsblvt** [comment]
Yeah, charset is always a problem :-/
Will fix that. Is already mentioned in #379, so this is a duplicate.

**Comment by sholan** [comment]
Sorry for dupe, github did not show me this.
Thank you !

**Comment by Wolfsblvt** [comment]
No problem, duplicate issues are better than none about a bug, they are easily closed :D
