### ISSUE TITLE
0.1.1 does not open

### ISSUE THREAD

**Issue by 607ch00** [Wolfsblvt/BlossomsPokemonGoManager#41]
Windows 10, JRE 1.8.0_102-b14

Attempting to login via Google auth. After entering key, program does not show a window.

0.1 still seems to work just fine.

**Comment by ghost** [comment]
Please delete your config.json file, and relaunch. Does this fix the problem?

**Comment by 607ch00** [comment]
Heh yeah it did, sorry I didn't think of that earlier. Thank you!
