### ISSUE TITLE
Move 2 abbreviated displays value for move 1

### ISSUE THREAD

**Issue by webdesignphilippines** [Wolfsblvt/BlossomsPokemonGoManager#418]
I'm trying to use rename to: %name%%move_type_1%%move_type_2%.

 It keeps renaming to iv, move1, and move1 again.

i tried %move_type_2% only and it still renames to move 1.

How to get it working?

**Comment by FernandoTBarros** [comment]
Duplicated #393 
Already fixed with #388 
Will be available in next released version or in the develop branch is already fixed if you want
