### ISSUE TITLE
Request : Toggle Enable or Disable for using Lucky Egg

### ISSUE THREAD

**Issue by d4rk4n93L** [Wolfsblvt/BlossomsPokemonGoManager#419]
need dev team for adding 1 function for enabling or disabling Lucky Egg, so we can adding EXP not only in bot process

**Comment by FernandoTBarros** [comment]
There is no option to use Lucky Egg without the GPS localization. 
Even within the app it remains disabled until your GPS is back again.
So, since the localization won't be added in this tool, there is no way to activate the Lucky Egg through this.
