### ISSUE TITLE
[Suggestion] Add additional data for detailed Ranking and Easy Level up feature

### ISSUE THREAD

**Issue by Or1j1n** [Wolfsblvt/BlossomsPokemonGoManager#42]
Hi, 

I was wondering if you would consider theses features : 
- Add data related to Gym Defense/Offense/Duel Ability from  https://docs.google.com/spreadsheets/d/1hcFo7-UGWx1k1u1BHOvDhq8foPeRr7YbX2jLjjJK0Qw/edit#gid=1036598933 to help with Ranking.
- Level-up to LvL X (Instead of clic.ok.ok \* 15 to level up a pokemon, it would be click.enter nb of level to powerup.ok.wait.done)
- Favorite pokemons

What do you think ?

P.

**Comment by Wolfsblvt** [comment]
Splitted all suggestions into own issues. Close this now here.
