### ISSUE TITLE
NAMED MY ACCOUNT NICKNAME

### ISSUE THREAD

**Issue by hardknoxni69a** [Wolfsblvt/BlossomsPokemonGoManager#425]
Hello Dev,
First and foremost thank you deeply for keeping this project alive we greatly appreciate your hard work. Now the problem here is I used a newer botted account that was being upgraded for a friend it did not have a nickname chosen yet. Upon logging into the account your bot gave my guy some jibberish nickname "FJnDbtSjkznTqt" I have used multiple programs and I have even used older versions of this from original repo and this has never happened to me before. Now this should be clearly stated in the readme or even upon launching the app as a warning. This is totally unacceptable. Excuse my b!tching I am just extremely disappointed sorry and thank you!

**Comment by Wolfsblvt** [comment]
Please provide more information.
What's your real nickname? What system are you on? Can you make a screenshot?

Oh, and can you stop writing capslock? That's hard to read.

**Comment by hardknoxni69a** [comment]
it was a botted account with no nickname set as it was for a friend now it shows up as that crap i almost used my main account that i botted for myself thank god i didnt i appreciate your work but this should be a serious warning noted in readme or something because it sounds ridiculous i know its a game but it made me furious

![image](https://cloud.githubusercontent.com/assets/21132978/18817643/cccb1bda-8333-11e6-8562-a59fbb952c2e.png)

**Comment by Wolfsblvt** [comment]
I don't understand. It is possible to create an account without a nickname? And our tool just **set** the nickname for you, and now it's set in Pogo as well?

That's kinda strange.

**Comment by hardknoxni69a** [comment]
if you create a new account and dont login and you just start botting it there will be no nickname set. Once you login to a device it will prompt you just like level 1. This account has now been given some trash name so we will no longer be able to set the original and change in future if needed

**Comment by Wolfsblvt** [comment]
Didn't they added "Change nickname" for one-time-use?

At least I don't know how this could be a bug here. We are using the PokeGOAPI-Java, which usually logs in the user and fullfills the tutorial.

**Comment by hardknoxni69a** [comment]
thats the problem i shouldnt have to use my one time use for that if you are using that api your client should have the setting to not set nickname or let user choose one but jibberish is ridiculous

**Comment by Wolfsblvt** [comment]
I am not sure if the Java API we use can work without setting the nickname. Guess you have to ask them there. The jibberish is not set by us, it's made in their API.
Take a look here, it's the [PokeGOAPI-Java by Grover-c13](https://github.com/Grover-c13/PokeGOAPI-Java).
