### ISSUE TITLE
[Bug] Sorting

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#43]
If I sort columns Lvl, Atk, Def, Stam, HP and to Evolve it's not sorted properly:
9
8
7
6
5
4
3
2
15
14
...

**Comment by OSwoboda** [comment]
I made a power up and sorted according to IV before. After the power up it was sorted according to Id.

**Comment by weblue** [comment]
has anyone fixed this yet? if not I can do it

**Comment by Wolfsblvt** [comment]
No reason to fix that atm. We should work on it if @Blossomforth has redone the table model. Then we can really work on it.
And I guess he even wanted to do it himself. We made plans for it already.

**Comment by Wolfsblvt** [comment]
Changed the milestone now. Isn't such a big bug that we need to rework the old table model

**Comment by Wolfsblvt** [comment]
Fixed with PR #244, finally!
