### ISSUE TITLE
Feature request: export to exel file or print results

### ISSUE THREAD

**Issue by Madentist** [Wolfsblvt/BlossomsPokemonGoManager#431]
This feature would be very useful for thise who use this tool to plan their tactics. I like to know what pokes are better for defend and what - for attack, what attack types which poko have. So when I'm outside and can't use this tool it would be very handy to have all info printed or saved into an exel file in my cloud.

**Comment by Wolfsblvt** [comment]
Yeah. Duplicate of #63.
