### ISSUE TITLE
[Suggestion] Easier Evolve (Color-code evolvable and display how much you can evolve)

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#44]
1. Additionally to Candies and how many Candies are needed to Evolve, it would be nice to display how many of that Pokémon could be evolved.
2. Option to select the amount of Pokémon of one kind that can be evolved with lowest CP/IV (needs https://github.com/Blossomforth/BlossomsPokemonGoManager/issues/24 to be implemeted first)

**Comment by JaymerJaymer** [comment]
... to help with determining which CAN evolve, adding a small color icon next to the QtyCandiesOwned would help. 

I sort my list by IV%, then Name, then To_Evolve

I scroll down past the 0's, and then work my way examining each to see if Candy > Evolve.

A simple color marker right there would help.

thx

**Comment by Wolfsblvt** [comment]
Sounds like a good idea. But guess that have to wait until we rework the table a bit to make it color-coded.

**Comment by ferazambuja** [comment]
Maybe add two columns for now. "How many evolves you can do" and "count of how many of that species. 

Name   IV.     Candy. Evolves Count
Pidgey 83%   16          1         3
Pidgey 50%   16          1         3
Pidgey 40%   16          1         3

**Comment by Wolfsblvt** [comment]
This suggestion will continue in #123. We should just keep one issue for that.
