### ISSUE TITLE
percentageWithTwoCharacters() formatting issue with double percentages...

### ISSUE THREAD

**Issue by rokkett** [Wolfsblvt/BlossomsPokemonGoManager#440]
The change to double for the percentageWithTwoCharacters() call causes formatting issues (returns 33.333333333 vs 34).

Suggested fix:

  public static String percentageWithTwoCharacters(double decimalNumber) {
        int percentage = (int)Math.round(decimalNumber \* PERCENTAGE_FACTOR);
        return (percentage < PERCENTAGE_FACTOR) ? StringUtils.leftPad(String.valueOf(percentage), 2, '0') : "XX";
    }

Add back the Math.round() and cast the double to an int to truncate it to an integer.

Thanks!

**Comment by TJD8521** [comment]
This worked great in fixing my renaming issue. I have a feeling the change was made to resolve 100% IV showing up as XX and not 100 or 100%.

**Comment by Wolfsblvt** [comment]
Yeah, dunno why I changed it this way, must have missed something. Will be fixed alongside other things in the next PR.

@TJD8521 "XX" doesn't need fixing. That's intended for 100%.

**Comment by TJD8521** [comment]
@Wolfsblvt good to know. I wasn't sure. Keep up the great work. I love this utility.
