### ISSUE TITLE
Renaming bug

### ISSUE THREAD

**Issue by turri1210** [Wolfsblvt/BlossomsPokemonGoManager#446]
Every pokemon I rename using the code %iv_rating% is now renaming with XX no matter how are it's IV's.

**Comment by Wolfsblvt** [comment]
Yeah, found the error. Going to fix it.

**Comment by vdittz** [comment]
Hello!

The same thing is happening with the "%gym_offense_rating%" too, every mon is showing XX as Gym Rating

**Comment by Wolfsblvt** [comment]
Yep, the problem occurs at the check when to use "XX". Such differenec when using `10 * 2` instead of `10 ^ 2` :D

**Comment by dawnforge** [comment]
I kinda hoped it was in exposed code, instead of compiled code, alas it doesn't look to be.

**Comment by StPatty33** [comment]
Same issue with duel ability rating and duel ability.  Also, sad to see the individual move dps % gone.

**Comment by Wolfsblvt** [comment]
> Same issue with duel ability rating and duel ability. Also, sad to see the individual move dps % gone.

There are the Duel Ability Rating, Gym Offense Rating and Gym Defense Rating for that now.
They display the percentage of the best possible of this species. So that's an advanced movement rating :P

**Comment by StPatty33** [comment]
True, but it doesn't help us know which moves we should be looking for in the field.  If a Pokémon is 80% of the max for that species, are both moves 80%? One 100% and the other 60%?  It just prevents us from knowing how each of the moves contribute to the overall scores.  I love the addition of the new metrics (or will once we can rename again), but the move ratings are still quite useful on their own.

Thanks for all you do--still the best IV program in existence!

**Comment by Wolfsblvt** [comment]
I am planning on adding a "Species Window" or something like that in the future, where you can click on a species and you see detailed information like all moves and how good they are for which of those three values, etc.

But yeah, Maybe I will just re-add them back. With hideable columns in the future everyone can just decide on his own what columns he/she wants.
