### ISSUE TITLE
DeviceInfo for iOS

### ISSUE THREAD

**Issue by tronage** [Wolfsblvt/BlossomsPokemonGoManager#448]
I'm trying to configure this to use my own DeviceInfo, however the wiki isn't very descriptive of "what goes where".  It just tells me to go to Settings -> General -> About ...  But doesn't describe what fields we should put where.  

So specifically I have no idea what to put for model Boot since nothing in my about screen looks similar to that used by default.  For type I'm not sure if either of those are correct since they both have values that look similar, 

Essentially I'd like to use my own device info, and love the idea that this was incorporated, but without knowing the correct values to fill-in, I'm unable to use this properly and would request better documentation for what values to put where.  

Using an app "dev info" I think I found what goes in the other places:
modelBoot = system device type unformatted
model = device model
id = Device Signature?
brand = System name
type = system version?
model =model from Settings -> General -> About ??

But when I try to launch the program with these fields filled in, nothing happens (it doesn't start, it doesn't pop up the window to use PTC or Google, etc).  But if I delete the config.json file and let it create a vanilla one, it then opens properly.  So clearly I got something wrong in somewhere. 

I think the dev info app will provide the info needed, I just need to know specifically what to put where to get this working properly.  Thanks for any help in clarifying this!!!

**Comment by Wolfsblvt** [comment]
That's the difficult thing here. I don't know either what to put where for the device info.
I have researched a few hours. But I don't have the time to do an advanced research. Really sorry :-/

If someone other comes up with help here, that would be great.

**Comment by Chazn2** [comment]
On this topic, some unicode doesn't work on iOS (even 10). It'd be nice to have suggested alternatives, I'll let you know if I find any.

**Comment by Wolfsblvt** [comment]
Unicode is already planned. It will be costumizable what unicodes you want to use in the future.

**Comment by pat15312** [comment]
Hi guys,

You can use the iOS app "Lirium Device Info Lite - System Monitor" to get all the information you need for this. This is free to download from the App Store.

The UDID can be easily got by plugging your iPhone/iPad into your PC/Mac and opening iTunes. Where the device pops up in the corner, clicking on the Serial number will then show the UDID.

**That all said, I have put in all the information (as shown in the example on the "How to" page) into the config.json file and the program will not open when executed...**

Cheers,
Patrick

**Comment by Wolfsblvt** [comment]
I guess that's because some info is still wrong.
Can you make the app run with the default configuration provided in the wiki?

**Comment by tronage** [comment]
I can not.  Even with:

 "deviceInfo": {
        "useCustom": true,
        "custom": {
        "android": {
            "bootloader": "",
            "boardName": ""
        },
        "device": {
            "modelIdentifier": "",
            "modelBoot": "iPad4,9",
            "model": "iPad",
            "id": "3562002a3ec39ccf64eff96879219ad1",
            "brand": "iPhone OS"
        },
        "firmware": {
            "fingerprint": "",
            "type": "9.3.1",
            "brand": "Apple",
            "tags": ""
        },
        "hardware": {
            "model": "J87mAP",
            "manufacturer": "Apple"
        }
      }
}
which is straight from the wiki the app does not load (or do anything when I click the "runonwindows.bat")  BUT if I delete the config and let it use the vanilla one it launches no problem (as I described initially)

**Comment by FernandoTBarros** [comment]
@tronage I'm gonna try here again using the default values. Maybe something has changed in the API. 
@pat15312 Same for you. After I make it work with the default values, we try to find what value is breaking your app.

**Comment by pat15312** [comment]
@FernandoTBarros thanks mate :) I can confirm that the software will load if I use the default config file.

**Comment by FernandoTBarros** [comment]
As I expected, the "default" DeviceInfo has changed. Maybe the previous one has been flagged?
Look here:
![image](https://cloud.githubusercontent.com/assets/3437672/19155455/f2df6edc-8bb4-11e6-9b95-354a28a4230c.png)
So that config.json model for iOS in the wiki it's not the default one anymore.
@pat15312 Can you test your values merging with this actual default values where you cannot obtain your own config?

**Comment by FernandoTBarros** [comment]
Just updated the wiki with the new default DeviceInfo and mention your app suggestion @pat15312 .
Waiting for you guys testing now.

**Comment by pat15312** [comment]
@FernandoTBarros I've got this working now. :) It appears that there was one less "}" at the bottom of the script than there should have been. The only thing that was incorrect from the example in the Wiki was two of the brand fields were mixed up, but I see you've fixed this now. Cheers, Patrick

**Comment by FernandoTBarros** [comment]
Actually the old default DeviceInfo was mixed up that way. 
But great it works now. Could you manage to work either, @tronage?

**Comment by tronage** [comment]
@FernandoTBarros 
I was able to get it working with the default setup from the wiki, and then I plugged in my own data using the UDID and info from the app that @pat15312 provided. 

The next question is how do I know if it "worked"?  It loaded and I see my pokemon, so does that mean it is now using  my info and all is happy in the world?  Is there a way to check it?
Thanks!

**Comment by FlamingFox911** [comment]
I'd like to mention your links are broken in the Wiki:

https://play.google.com/store/apps/details?id=omorapps.build_inf (Wrong, missing an 'o') ->
https://play.google.com/store/apps/details?id=omorapps.build_info

https://play.google.com/store/apps/details?id=com.appzdevelopers.anddevinfo (Wrong, missing an 'f') -> https://play.google.com/store/apps/details?id=com.appzdevelopers.anddevinfof

Writing this in case people are confused.

> And after figuring out your wiki, I realized that the ALL CAPS is the word to look for in the App, and in the brackets is where to put your info in the config.json.  (i.e. BOARD (android.board) means find 'BOARD' in the app, and copy the information show there into android -> board). 

Everything works now ^-^

**Comment by Ryanizleee** [comment]
This is what I had on the bot which I'm running for quite some time, and worked fine. Hope this helps =

 "DeviceConfig": {
    "DevicePlatform": "apple",
    "DevicePackageName": "custom",
    "DeviceId": "2022af5f9d16c1c8d687fa35c237fa1f8bc97b49",
    "AndroidBoardName": "unknown",
    "AndroidBootloader": "iBoot",
    "DeviceBrand": "Apple",
    "DeviceModel": "iPhone 6 Plus A1524",
    "DeviceModelIdentifier": "A1524",
    "DeviceModelBoot": "iPhone7,1",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "N56AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": "release-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "apple/apple/unknown_9.3.3/MMB29M1157729:user/release-keys"

**Comment by FernandoTBarros** [comment]
> I'd like to mention your links are broken in the Wiki:
> 
> https://play.google.com/store/apps/details?id=omorapps.build_inf (Wrong, missing an 'o') ->
> https://play.google.com/store/apps/details?id=omorapps.build_info
> 
> https://play.google.com/store/apps/details?id=com.appzdevelopers.anddevinfo (Wrong, missing an 'f') -> https://play.google.com/store/apps/details?id=com.appzdevelopers.anddevinfof
> 
> Writing this in case people are confused.

yes @FlamingFox911 ! I've just corrected the links in the wiki now! Thanks for the tip!

> And after figuring out your wiki, I realized that the ALL CAPS is the word to look for in the App, and in the brackets is where to put your info in the config.json. (i.e. BOARD (android.board) means find 'BOARD' in the app, and copy the information show there into android -> board).
> Everything works now ^-^

Yes, I'm gonna use your text to try to explain that in the wiki too!
