### ISSUE TITLE
"Move rating" column is not present

### ISSUE THREAD

**Issue by sebium** [Wolfsblvt/BlossomsPokemonGoManager#450]
Hi, in the previous version we had "move rating" column but in the new version they disappeared :(.

why ? it's a bug ? can you had these two column plz ?

Thx.

**Comment by Wolfsblvt** [comment]
I don't understand.
I can re-add them if its really wanted, but I always thought them to be a temporary solution, until I have a better rating set up. Which I have now.

Moveset Rating was raw dps analysis, nothing more. The new **Duel Ability Rating**, **Gym Offense Rating** and **Gym Defense Rating** do much more. They weigh against the best possible of the Species, for the exact thing that you want to know. Gym Defense, Gym Offense or raw damage.

So you should see those three Rating columns as advanced and more detailed moveset rating.
Cause they include moveset and IVs.

**Comment by StPatty33** [comment]
The Duel Ability rating (for the species) is exactly what I had been looking for many weeks ago when I started using the move % ratings (comparing dps% to the species best).  After using the dps% of the species max, I now see that it's beneficial at times to know what the value of the individual moves are, not just the overall.  If it's not a great deal of trouble, it would be very useful to have them back as an option.  I feel these are much more useful than about 75% of the other metrics, haha!

**Comment by Wolfsblvt** [comment]
The table gets quite overloaded with columns, which really slows the tool down when used on slow computers. But that will be fixed with hideable columns. So I will add them back at latest when I've implemented hideable columns.

**Comment by Wolfsblvt** [comment]
Like you can see here, PR is already open, so will be back in in the next version.
