### ISSUE TITLE
Renaming with pattern %name_#% won't work if PokemonName is shorter than it

### ISSUE THREAD

**Issue by PinkyH** [Wolfsblvt/BlossomsPokemonGoManager#454]
It seems the program panics if it finds a name shorter than a pattern :P

E.G.: If you are doing a batch-rename with pattern %name_8% and there's a Pidgey [6] on the list, the process will stop completely with no warning.

**Comment by Wolfsblvt** [comment]
Have to check. Should work now with the newest develop stuff though.

**Comment by Sanaki** [comment]
Can confirm this, came here to see if it was reported yet. Checked on latest compiled release, not dev.

**Comment by Wolfsblvt** [comment]
Yeah, you are right. PR is open for that now (:
