### ISSUE TITLE
Renaming with %iv_rating% is broken in 0.1.3

### ISSUE THREAD

**Issue by boomschtick** [Wolfsblvt/BlossomsPokemonGoManager#457]
In every case that I have tried, using %iv_rating% results in a XX in the Nickname.  No matter what the actual IV's are.

Using %name_4% %iv_rating% %hp% results in:

Pidg XX 56

**Comment by pat15312** [comment]
I can confirm that this is also happening for me.

**Comment by Wolfsblvt** [comment]
Yep. Duplicate of #446.
