### ISSUE TITLE
CP Evolved not correct for Eevee's on 0.1.3

### ISSUE THREAD

**Issue by boomschtick** [Wolfsblvt/BlossomsPokemonGoManager#458]
I caught two level 28 Eevee's this morning.  When I look at them in 0.1.3 the CP and CP Evolved is the same.  In 0.1.2, the first is 757 and 2077 evolved.  The second one is 769 and 2096 evolved.

I have not been able to observe this same problem with any other species up to this point.

**Comment by Wolfsblvt** [comment]
I've switched my own calculation of those CP values to the one the APi provides. Seems not to work for Eevees. Great.
Will fix that soon.
