### ISSUE TITLE
[Bug] Encoding

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#46]
`Nidoranâ`
instead of ♂ or ♀

**Comment by Wolfsblvt** [comment]
Encoding is a known problem. We are working on that.

**Comment by OSwoboda** [comment]
I've built the newest version and the Coding is more messed up than before. Even Pokémon is now not properly displayed and there are no Pokémon loaded.

**Comment by Wolfsblvt** [comment]
Oh, sorry that it wasn't that clear. We haven't released a new version with that fix already. I just closed the issue cause it works in the development version.

**Comment by OSwoboda** [comment]
As I said: I've built the latest version from master and it's more messed up than the release version. Or where can I find the development version when it's not here on master?

**Comment by Wolfsblvt** [comment]
Nah, master is correct. It worked for us, but seems to be some issues still then.
Maybe it will be fixed with the release version and has something to do with the encoding set for the build on your side?

Either way, I will re-open that issue until it is solved.

**Comment by wullxz** [comment]
@OSwoboda it would help us, if you could tell us more about how you built the project.  
Which IDE are you using? Do you use a build system?  
Have you tried building it with `mvn package` (requires Maven to be installed)?

Also, does your IDE/Editor show the encoding it has detected for the files? If so: what does it say?

**Comment by OSwoboda** [comment]
I've testet it today on my home desktop and encoding was fine. I'll test it on my work computer on monday again, there I had the problems. If there are still problems I'll report you exactly my setup.

**Comment by Wolfsblvt** [comment]
Waiting for @OSwoboda's input then.

**Comment by OSwoboda** [comment]
Everything is fine now, don't know what it was. Can be closed.
