### ISSUE TITLE
Android DeviceInfo Names and Locations

### ISSUE THREAD

**Issue by FlamingFox911** [Wolfsblvt/BlossomsPokemonGoManager#465]
I have probably tried a dozen programs, and I can't find the information listed in the Wiki, and I am starting to believe that the list is out of date.

I am running a 6.0.0 (Marshmellow) on my Moto G2.

Can someone please give me the exact names and locations to be looking for?

**Comment by Wolfsblvt** [comment]
Can you ask in the question issue #448? Guess we should keep that as the general question place.
The wiki got recently updated. Have you checked the new info? An app is mentioned there too.
