### ISSUE TITLE
Move Set Suggestions (Ordering and Best/Worst)

### ISSUE THREAD

**Issue by FlamingFox911** [Wolfsblvt/BlossomsPokemonGoManager#466]
Just a suggestion, primarily because a Pokémon's move set is _**generally**_ more important than their IV, could you have the columns for Move 1 and 2 sort by their DPS rather than alphabetically?

Also, if possible, it would be nice to see from a glance that a Pokémon has already the best possible moves. (i.e. I could look at the Move Set column and if I see Green, for example, I know he has the best move for that column.)

**Comment by Wolfsblvt** [comment]
Have you seen the Gym Defense Rating and Gym Offense Rating columns?
They do exactly what you want. They check against the best possible moveset + iv of that species.
Sure, iv is still included, but it really doesn't weigh much.

So if you want to see if you have the best offensive moveset, just check the rating column. Same for defensive then.

Guess that's what you want?

**Comment by FlamingFox911** [comment]
Ah, yes. That's what I was looking for. And its highlighted as such. Thanks :)
