### ISSUE TITLE
Sort by Move DPS

### ISSUE THREAD

**Issue by mreinhardt** [Wolfsblvt/BlossomsPokemonGoManager#468]
Instead of having DPS in parenthesis on the move column, it would be nice to have separate columns for `Move #` and `Move # DPS`  so that it's possible to sort by DPS.

**Comment by Wolfsblvt** [comment]
What about sorting on dps, not sorting on names at all?
Guess there is like no reason to sort after names. You can still filter the table for move names.
Quite sure there is already an issue about it.
