### ISSUE TITLE
Wiki Page missing details

### ISSUE THREAD

**Issue by KennyLMQ** [Wolfsblvt/BlossomsPokemonGoManager#469]
I'm an Android user and the steps listed in the link ([https://github.com/Wolfsblvt/BlossomsPokemonGoManager/wiki/Using-your-own-DeviceInfo-to-connect-to-API](url)) seems to be missing some details. 

It's mentioned that device.brand gets the value from both BRAND and DEVICE. So which one should it be?

Also there's no mention of what values to use for device.modelBoot and android.boardName. Are they supposed to be left blank? If so, it would be a good idea to mention it.

**Comment by FernandoTBarros** [comment]
Ok, corrected these values now: "BRAND" is "firmware.brand" and "DEVICE" is "device.brand"

Device.modelBoot for Android apparently is always "qcom". It's on the wiki now too.

And "android.boardName" is BOARD on Build Info app. Corrected this in wiki too!
Thanks!

**Comment by KennyLMQ** [comment]
Thanks for the quick work!
