### ISSUE TITLE
Add a new "version" just to warn users. 

### ISSUE THREAD

**Issue by dec0dedab0de** [Wolfsblvt/BlossomsPokemonGoManager#471]
I was thinking it may be nice to create a new point release, just to notify your users that there is increased risk since the API changes happened.  Even if it is just the same code, with the warning in the release notes.

**Comment by Wolfsblvt** [comment]
We have added a notice on discord and on the description of this GitHub project, right above.
I hope that is enough. Most people don't want to get annoyed by a continiously popping up message that doesn't do anything specific.

No one knows if the risk is really increased, to be honest.
