### ISSUE TITLE
How should I interpret  these figures?

### ISSUE THREAD

**Issue by adr-sit** [Wolfsblvt/BlossomsPokemonGoManager#472]
First time user of this tool. Great and handy tool.

![new picture 2](https://cloud.githubusercontent.com/assets/21173226/19336659/c7c5ae4c-913f-11e6-85ad-67ccc089431a.gif)

How should I interpret the figures in colour? Are they good, bad? What are the max and min values of these columns?

The dialogue below mentioned the highest duel ability, gym offence and defence value. Those numbers are very very huge. Is same formula being used to calculated?

**Comment by Wolfsblvt** [comment]
I thought the colors were pretty self-explanatory :D
Green is best. Yellow is average, red is bad.
More exact:

| From | To | Color |
| --- | --- | --- |
| 0% | 33.333% | Fully **RED** |
| 33.333% | 66.666% | Transition from **RED** to **YELLOW** |
| 66.666% | 100% | Transition from **YELLOW** to **GREEN** |

That means the min and max values are 0% and 100%, limited like percentages :P 

The numbers printed in the console are the correct values that are calculated, yes. They have very complicated formulas.
The columns itself do display the Percentage weighted against the best possible one. In that way we have a much more readable number, like percentages (:

What the columns mean:
Duel Ability is like DPS only if you don't dodge anything. Gym Offense and Gym Defense are what they mean. They rate how good you are in defense or offense for gyms. Then there are all three columns with "Rating" after it. That's a cool one. They don't rate against the best possible Pokémon, but more against the best possible Pokémon of that Species. So it kinda rates the moveset :P
The move rating columns just rate the raw DPS of the single moves against the best possible move of that Pokémon.

**Comment by adr-sit** [comment]
Thanks. You are 1 of the most patient and responsive chaps ever seen in github.

Please don't mind I drill into some more details and check if I am on the right track.
1. The "1st three Rating" columns of Duel, Offense, Defense compare pokemon of same species. When decide which 1 to drop/keep (same species). I should consider these 3 ratings + move rating
2. When consider which one to evolve / power up (across different species), I should look at the The Duel, Offense and Defense columns in the middle

**Comment by Wolfsblvt** [comment]
Yes, that should be overall correct.
I use the Rating columns to decide if one Pokémon should be transferred (crap), or if it is worth to invest the candy to power-up.

Then I use the general columns (without rating) to decide which Pokémon to take for gyms, attacking or defending. There I look at the rating, the types (type advantage and stuff) and of course the CP.

And thank you for the compliment ^.^

**Comment by QuadTog** [comment]
Hey mate.

To further clarify:
1) The 'First Three Rating" columns display the effectiveness of your Pokemon at either Attacking or Defending gyms. They already include Move DPS as sometimes a lower IV Pokemon will perform better with a top tier move set or vice-versa.

2) Yup! Although this won't account for evolving into a better move set.

**Comment by adr-sit** [comment]
Thanks both for friendly advice.

When evolving a certain species, the moves set of the evolved species is unpredictable, could be better or worst, isn't it?

**Comment by Wolfsblvt** [comment]
Yes. Movesets are random, re-thrown after evolve. Nothing to predict in any way.

**Comment by QuadTog** [comment]
I'm actually looking into this. We may be able to predict move-sets off the Pokemon uID, still rumours at this stage but worth investigating.

**Comment by ieatfrisbees** [comment]
I'm so, so sorry to dredge this up 1.5 months after it being marked closed, but I just have one question about this comment from QuadTog:

"The 'First Three Rating" columns display the effectiveness of your Pokemon at either Attacking or Defending gyms. They already include Move DPS as sometimes a lower IV Pokemon will perform better with a top tier move set or vice-versa."

Does that mean, for example, a Vaporeon with good IVs but WG/WP moveset will probably have a lower "rating" in these categories than a Vaporeon with lower IVs, but a better moveset like WG/HP (thus indicating the second Vaporeon is the better one do invest candy/stardust into)? And also, say you have two Vaporeon that are the same level with the same moves, will the one with the higher IVs get the better rating here or will the values be the same?

And then branching off that, the next three "duel"-related columns have the same idea, but applied across all species of pokemon and not just within the same species? 

Again, so sorry to bring this up, and that's probably what your previous comments are saying, but I just needed to spell it out how it appears to me so I can really get a hold on it. 

Thanks SO much for all you do, this is a phenomenal tool!!!!

**Comment by Wolfsblvt** [comment]
@ieatfrisbees I guess all your questions are answered with yes.
You already understood it :P

**Comment by ieatfrisbees** [comment]
Okay! Thank you. Appreciate you wading through my word vomit to confirm those suspicions, @Wolfsblvt 

Actually! One more thing-- pretty sure this is also a "yes" but those ratings (both intra-species and inter-species) are independent of the individual mon's current CP/level, right?

**Comment by Wolfsblvt** [comment]
Exactly. They are just based on the IV and the moveset.

**Comment by thisischrys** [comment]
Dunno about you guys, but this should be in a FAQ or something IMHO

**Comment by Wolfsblvt** [comment]
@thisischrys Yes. But who has time to write a FAQ and keep it up to date? :P
