### ISSUE TITLE
Just updated PoGO, this application doesn't load anymore

### ISSUE THREAD

**Issue by Bajlomanz** [Wolfsblvt/BlossomsPokemonGoManager#474]
"Unfortunately, your login has failed. Reason:

AsyncPokemonGoException: Unknown exception occurred.

This is try number 1.

Press OK to try again."

I got this error 7 times in a row, eventually gave up.

**Comment by Wolfsblvt** [comment]
The app working for you atm?
Official servers are down for a few hours already.

**Comment by Bajlomanz** [comment]
I was having issues logging into the servers at 7 PM EST, but I have been able to log in and stay logged in for the past 15-20 minutes.

**Comment by Wolfsblvt** [comment]
I can login pretty fine with this tool (:

**Comment by Bajlomanz** [comment]
PTC or Google?

**Comment by Wolfsblvt** [comment]
Google. Using the App Password option.

**Comment by Bajlomanz** [comment]
Question:

When I go to the page on Google that gives me an app password, I am supposed to copy and paste that into the "Password" prompt, but the username, am I supposed to put my gmail email? Or my in-game username?

**Comment by Wolfsblvt** [comment]
It is the gmail username.
