### ISSUE TITLE
IV% will be shown as XX if it is 100%

### ISSUE THREAD

**Issue by hkguy80** [Wolfsblvt/BlossomsPokemonGoManager#475]
in version v0.1.2.
not sure if it is fixed in the latest version.

**Comment by Wolfsblvt** [comment]
Yeah, it was changed back in the column to a real percentage (e.g. `97.92%`) like it was before.

Why do you still use v0.1.2? xD There is [v0.1.4](https://github.com/Wolfsblvt/BlossomsPokemonGoManager/releases/tag/v0.1.4) out already :P

**Comment by hkguy80** [comment]
I can't use 0.1.4 unless it can sort the "Evolved CP" ... 
: (
