### ISSUE TITLE
White font is hard to read for colored cells

### ISSUE THREAD

**Issue by GoMattGo** [Wolfsblvt/BlossomsPokemonGoManager#479]
When a row is selected the font for that line turns white, and for any columns with yellow shading (eg. 66% IV) the writing is very hard to read. Can the font for the colored squares remain black?
Thanks

![white font](https://cloud.githubusercontent.com/assets/22924036/19500830/52d2830a-95e8-11e6-8ea7-1d51dba7efb0.png)

**Comment by Wolfsblvt** [comment]
Yeah, planned already. I will see what I will do, but be sure it will be better readable.
