### ISSUE TITLE
[Suggestion] After an action, sort is lost.  Can u just update/delete the rows in the table

### ISSUE THREAD

**Issue by JaymerJaymer** [Wolfsblvt/BlossomsPokemonGoManager#48]
I know its simpler the way you do it, but if I sort on 3 columns and then work through my list, doing a simple Transfer makes me "lose my place" since you refresh the list.   I have to resort and find where i was.

Also, I think its awesome the way you search... typing EEVEE finds the entire lineage, not just EEVEE.  Nice touch. 

Saw you guys on discord last night and am glad you got a new version out.  very nice.  WOOT!

**Comment by Wolfsblvt** [comment]
There is already an issue with that: #43
