### ISSUE TITLE
Please implement new pgoapi

### ISSUE THREAD

**Issue by nomisunrider** [Wolfsblvt/BlossomsPokemonGoManager#485]
https://github.com/pogodevorg/pgoapi/

This will help with preventing bans, no?

**Comment by Wolfsblvt** [comment]
Maybe? We still don't know how Niantic flags.
We can't use the Python API though, our tool is written in Java and uses the [PokeGOAPI-Java](https://github.com/Grover-c13/PokeGOAPI-Java).
So we have to wait until this API is updated.

**Comment by nomisunrider** [comment]
I believe it is updated now.

https://github.com/Grover-c13/PokeGOAPI-Java/pull/790

**Comment by Wolfsblvt** [comment]
True. Will update it then.
