### ISSUE TITLE
Please update calculations according to new base stats

### ISSUE THREAD

**Issue by tonireha** [Wolfsblvt/BlossomsPokemonGoManager#486]
Niantic has [updated the base stats](http://pokemongo.nianticlabs.com/en/post/cp_update/
) for almost all pokémon
The Silph road research has found out the new stats: [reddit link](https://www.reddit.com/r/TheSilphRoad/comments/5e6jev/silph_research_group_on_cp_balancing/), [stats spreadsheet](https://docs.google.com/spreadsheets/d/1_WS9FIGSlKVk6XAJTE3TxXIqlBPIQ5Lsx5qifE72vXY/htmlview?usp=sharing&sle=true)

Please update the cp calculations according to these new base stats. 
The current cp, as well as the "CP Evolved" for fully evolved pokémon still seem correct, but Max CP (both cur & 40), Max CP Evolved (both cur & 40), and CP Evolved for not fully evolved pokémon need to be updated.

**Comment by tonireha** [comment]
I'm unsure if gym calculations are affected since I've never understood them :blush:

**Comment by Wolfsblvt** [comment]
Yeah, will look into what we actually have to change. Thank you.
