### ISSUE TITLE
Captcha when doing bulk operations

### ISSUE THREAD

**Issue by poiuytrezaur** [Wolfsblvt/BlossomsPokemonGoManager#496]
When receiving a captcha because you are doing bulk operations (happened to me on evolving) PGBM receives a captcha request. If not completed it crashes and you get (IP banned/Token banned ? (403 error))
Here's a link about knowing if there's a captcha and solving it manually 
https://www.reddit.com/r/pokemongodev/comments/5bwzq7/howto_manually_perform_captcha_from_api/

In the comment, an example of python implementation :
http://pastebin.com/7F6BZFZe

**Comment by adr-sit** [comment]
Do you mean you are banned?

**Comment by poiuytrezaur** [comment]
Ip is banned but account is up

**Comment by nhahtdh** [comment]
Instead of spamming the server with large number of requests and trigger the captcha, can we play nice and insert time delay between each request?

**Comment by poiuytrezaur** [comment]
For me it was sending 600+ requests. 1 second delay between requests would take 10 mins to load pokemons...

**Comment by Wolfsblvt** [comment]
> Instead of spamming the server with large number of requests and trigger the captcha, can we play nice and insert time delay between each request?

That's default state of this tool. All operations have configurable delays between the bulk steps.

> For me it was sending 600+ requests. 1 second delay between requests would take 10 mins to load pokemons...

Getting inventory (pokemon) is one call, not one for each Pokémon.

**Comment by poiuytrezaur** [comment]
Yeah but the locations aren't 1 call at all ! (Which cause the error)

**Comment by nhahtdh** [comment]
> That's default state of this tool. All operations have configurable delays between the bulk steps.

Oh, just found that option in `config.json`. I never used the tool for transferring or evolving, so I'm not aware of how it works.

----

Regarding the location, I guess you can add an option to disable resolving the coordinate. Not everyone needs that information.

**Comment by Wolfsblvt** [comment]
Locations aren't queried from Niantics server or API. Thate Google Maps.

**Comment by FernandoTBarros** [comment]
On 1.7.0 version captcha solver is available to when a captcha is required to continue.
