### ISSUE TITLE
SUGGESTION -  Highlight Gen 2 Pokemon Candies

### ISSUE THREAD

**Issue by carloshax** [Wolfsblvt/BlossomsPokemonGoManager#504]
It would be great if you could highlight the pokemon whos candies will be needed for Generation 2 pokemon. This will make it easier to remember to save those candies for gen 2 and not use the candies by mistake.

**Comment by Wolfsblvt** [comment]
Hmmmh. Maybe we can do that, yes.
We would need a list by hand which candy is needed for gen2 though.
Can you provide a list, containing the Pokémon Ids which candy is to be saved? Or family Ids. Whichever works better.

**Comment by nhahtdh** [comment]
From [reddit](https://www.reddit.com/r/TheSilphRoad/comments/4w9w5k/list_of_gen_1_pokemon_that_evolve_in_gen_2_and/)
-   Golbat -> Crobat
-   Gloom -> Vileplume/Bellossom
-   Poliwhirl -> Poliwrath/Politoed
-   Slowpoke -> Slowbro/Slowking
-   Onix -> Steelix
-   Chansey -> Blissey
-   Seadra -> Kingdra
-   Scyther -> Scizor
-   Eevee -> Jolteon/Vaporeon/Flareon/Espeon/Umbreon
-   Porygon -> Porygon2

**Comment by Wolfsblvt** [comment]
Not needed anymore.
