### ISSUE TITLE
Call for donation link

### ISSUE THREAD

**Issue by leoli-dev** [Wolfsblvt/BlossomsPokemonGoManager#505]
Wow, you guys are doing a great job, my wife and I use it every single day for renaming and evolving. My Java skill doesn't allow me to make any contribution to the project, but I'm wondering if there is a donation link so that I can buy you a coffee.

Anyway, thank you so much!

**Comment by Wolfsblvt** [comment]
A detailed answer concerning donations can be found on reddit here:
https://www.reddit.com/r/pokemongodev/comments/5emack/blossoms_pogo_manager_is_updated_to_v15_dev_has/

Hope that helps :D

**Comment by leoli-dev** [comment]
@Wolfsblvt Got it, thanks again
