### ISSUE TITLE
Feature Request: Multiple user login

### ISSUE THREAD

**Issue by leoli-dev** [Wolfsblvt/BlossomsPokemonGoManager#507]
Hello, I need this feature for a long time as I manage two accounts in one Mac: one is mine, and the other one is my wife's. 

For now, I have to rename `config.json` & `location.json` each time before I run the app, it would be nice if we can manage it inside the app.

**Comment by Wolfsblvt** [comment]
`location.json` can be one combined file, that's fine. It only caches locations, so if your wife has already caught a Pokémon at location xyz the location must not be queried for you again :D

I can consider this feature though. Would be useful for the botting part of the user base too. (Even though I don't like botting, I accept that they are here)

What's keeping you from making to seperate folders, named after your account and putting the tool in each, so duplicating it? Then you just have to use the correct folder for now.

**Comment by leoli-dev** [comment]
@Wolfsblvt Oh no, I didn't think about it! You're definitely right, I can duplicate it into two folders. Ok then, it's good enough for me.

**Comment by Wolfsblvt** [comment]
Nice (:
And another problem solved :D
