### ISSUE TITLE
Usage of multi-transfer API function

### ISSUE THREAD

**Issue by SlimeKingz** [Wolfsblvt/BlossomsPokemonGoManager#513]
since last update you can select multible pokemons to transfer. will there also be a update of this project that uses that mothed to instand transfer?

**Comment by Wolfsblvt** [comment]
I can implement it, if the java api itself implements the call based on the real api.
But sadly I am quite sure this won't happen :-/

**Comment by Wolfsblvt** [comment]
Included with #548
