### ISSUE TITLE
DPS values incorrect

### ISSUE THREAD

**Issue by phronx** [Wolfsblvt/BlossomsPokemonGoManager#52]
Move damage was updated on 29th of July, but the old DPS values are still being used. For example water gun got nerfed from 20dps to 12dps (15 dps with STAB).

**Comment by Ljaysoft** [comment]
Will fix dps soon, I was using a rough calculation, going to use more accurate ones

**Comment by Wolfsblvt** [comment]
PR is merged, so this can be closed
