### ISSUE TITLE
Alter best moveset unicode to better suit iOS

### ISSUE THREAD

**Issue by sthewissen** [Wolfsblvt/BlossomsPokemonGoManager#528]
The current implementation for the unicode shield and sword to determine best movesets doesn't work on iOS. The icons won't show. I would very much like the ability to have a setting in the config where it takes the character to use for best attacking moveset, best defending moveset or both (if attacking and defending is the same). Currently I use a ~ for best defending, a • for best attacking and a + for both. Making it a setting means people can do it however they prefer.

**Comment by NIKLA5** [comment]
The unicode for ICE, FIGHTER, FAIRY does not work on my Android (one plus 3)
how can i change the unicodes used in the files? Regards Niklas
I loved this app from the start!

**Comment by Wolfsblvt** [comment]
Yeah, Unicode symbols do not work for many phones. We can't provide working ones for everything though.

So we will implement #301 and you can define symbols yourself (:
