### ISSUE TITLE
Add the option to leave out moveset type 2 if its the same as 1

### ISSUE THREAD

**Issue by sthewissen** [Wolfsblvt/BlossomsPokemonGoManager#529]
Like the title says, currently an all Electric moveset gets named **ELEL** but I would love the option to have it simply say **EL** when both moves are the same type.

**Comment by Wolfsblvt** [comment]
That's a strange request. I get that it would be cool to save up characters. But if it doesn't count for most of the Pokémon, how can you do bulk renames with the character limit?

For me, it doesn't make sense :-/
