### ISSUE TITLE
Question: Is it possible to retrieve the location of a 'seen' Pokémon?

### ISSUE THREAD

**Issue by just-Addict** [Wolfsblvt/BlossomsPokemonGoManager#532]
Got a question and if it's possible, I very much would like to have this added on the to-do list as feature request.

Is it possible to retrieve the location where you have seen a Pokémon if you didn't manage to catch it?
The pokedex only shows the silhouette and the details screen only shows the name and index number but sadly doesn't mention where you encountered it.

When I first started playing I encountered a Gyarados, Snorlax, Dragonite and a Tauros but I was still so low leveled I couldn't manage to capture them with the limited number of balls I had at the time. Sadly due to reasons my memory is crap, and I didn't realize at the time how rarely I would encounter these so didn't make a note where it happened.

If it is possible to retrieve this information than at least I would know where they might spawn again in the future...

**Comment by cris11368** [comment]
That information is only stored for pokemon you actually catch. The historical data will only be available on maybe a map that was scanning the area. I highly doubt niantic keeps a record of everything that has spawned ever.

**Comment by Wolfsblvt** [comment]
@cris11368 Answered it correctly. It is not possible to retrieve such kind of information.
