### ISSUE TITLE
Evolvable column always assumes "Transfer After Evolve" even if not ticked.

### ISSUE THREAD

**Issue by just-Addict** [Wolfsblvt/BlossomsPokemonGoManager#536]
While creating a spreadsheet to copy/paste the output of BlossomsPokemonGoManager, I suddenly noticed something odd. To be honest, I've never given the other columns besides IV values much thought so didn't notice this before.

I've got several mons for which the evolvable value is wrong. I do NOT have "Transfer After Evolve" ticked so it should NOT take into account the candies I would get from transfering the evolved forms. I DO however have that many evolvable forms to explain the difference. But as I said, I do not have the "Transfer..." option checked, so it should NOT take the number of evolvable forms into account.

Examples: 
having 2 Pidgey's and 2 Pidgeotto's and 104 Pidgey candies
- (costs 12 to evolve the Pidgey's) but the evolvable columns says 9 instead of 8 

having 3 Weedles and 34 Weedle candies 
- (costs 12 to evolve) but the evolvable column says 3 instead of 2

having 3 Eevee's and 73 Eevee candies 
- (costs 25 to evolve) but the evolvable column says 3 instead of 2

As you see it takes the number of mon's into account assuming evolved forms would be transferred to make up for the number of candies short in order to evolve the one counted extra.

**Comment by fcphantom** [comment]
Apparently you are missing something about the number of candies you need.  Whenever you evolve, you get one of the candies back.  ie. if you have 12 candies, you can evolve a pidgey and you will end up with one candy after evolving.  That's before you transfer anything.  Therefore evolving 3 Eevees requires 73 Eevee candies (73-25+1-25+1-25+1) and you will end up with one candy left.

In other words it's not assuming "transfer after evolve".  It's correctly calculating how many you can evolve before transfers.

**Comment by just-Addict** [comment]
damn, completely overlooked that... :) you're right.
