### ISSUE TITLE
 failed to get game data from the server

### ISSUE THREAD

**Issue by Macgyver7th** [Wolfsblvt/BlossomsPokemonGoManager#538]
Since of 01/23/17 when the 0.53.2 update launched I can't login into my Pokémon go account keep getting, unable to authenticate, failed login, failed to get game data from the server, in that order, I have a android turbo 2 using the Google sign in. The last time I played the game it was shutdown after a pokestop  daily bonus spin was done in the morning of 23rd later that day when the update pushed thru the game started running this error flow chart as listed above and pictures I'll attach that started in .53 update. didn't think anything of it and filed a simple bug report to Niantic's pokemon go website hoping it was the issues they may have with the server due to them booting up the south Korean server at the same time as the update. The Lame part of contacting Niandick's... lol is they don't do the hey we hear you man, this is a issue that can be fixed or is going to be fixed e-mail exchange in fact they state that they dont reply at all unless they want information from you in the matter... SO i freaked out and thought I got banned for using the the tools, when I google'd the issue and had mixed reviews on what the codes I was popping ranged from banned to fucked up server, got The Pokémon Company International website which loselly handles all pokemon games from what I understood. was like we don't handle the app even know we have a link for pokemon go here, but ya we kinda heard that was an issue they had... so I waited till the the next update to see what would happen... In the down time thanks to the help of my friend that I pokemon go hunt with told me my Dragonite and his alakazam was still in the top of the gym we took several days prior to the update. So my account still is active on the pokemon server I just can't connect to it. So after factory resetting my phone, turning on google two step verification, changing my password, taking the app permission data off the google website so it would have to resycn to the server. all the time I didn't use the tool in fear of it being some crafty niantic poketrap to catch me iv cataloging and evolving and transferring the pokemon with the tool. Which I use the tools to help not kill my phone with the pokemon go app lol....Then .55 update drops I feel my hopes rise wanting to play the game again after a week of failed to get game data from the server and no fixes... still the same thing happens...only faster this time lol... read on niantic's site that Your account is banned if you see the “Your account has been suspended for violating the Terms of Service”  and has a cool picture of it next to the I think I might be banned hot list category lol, which is funny they have need for that by the way... so I break down and delete the pogo management tool 1.6 and look on the site to download a newer version of it before attempting a new logon via the tools to the pokemon go server. When I did I saw that there was a new pull request open on the .53... so is this an issue that pertains to that pull request or is the data that's on the pokemon server going not connection right, which my only hope is to get their attention by filing another bug report or risk asking the question of can they fix my account via the banned appeal approach to talking to a real person that could help me fix the issue...  which bring me to a concern would this put your program at risk of being found out during the 2 weeks and 2 days that I haven't played the game I read a lot about the pokemon go new to see if anyone else was sharing the same issue, which some were and I found a few article that said during the .53 update the hand out cease and desist letters to pokemon go map app tools, which is nothing I use, the blossom tool is the only thing I use to be honest... I just don't want to bring niantic eye's to your direction, if doing a can you help me niantic, with the banned appeal limewire being use.... anyways sorry for the long detailed message but thanks for the time in reading this, For some reason when I signed up here to github in December with the baby pokemon question which you answered, my account some how became flagged lol, I'm just a guy from California trying to catch pokemon each day enjoying cardio in the process., lol. hopefully you can shed some light on some of these issues I listed in the message above.
![screenshot_20170125-085151](https://cloud.githubusercontent.com/assets/24599625/22717953/bedfece2-ed52-11e6-9417-10740ce263d8.png)
![screenshot_20170125-085714](https://cloud.githubusercontent.com/assets/24599625/22717969/dbfb7706-ed52-11e6-8728-b737c5a2dcf1.png)
![screenshot_20170123-183737](https://cloud.githubusercontent.com/assets/24599625/22717975/e2d6deb2-ed52-11e6-80a5-6a053a5f8d7b.png)
![screenshot_20170124-102405](https://cloud.githubusercontent.com/assets/24599625/22717983/ed13b486-ed52-11e6-9b37-2f173a00a296.png)

**Comment by Macgyver7th** [comment]
![login issue](https://cloud.githubusercontent.com/assets/24599625/23391774/1e21c228-fd2c-11e6-9b8f-88f8c74ee6f7.jpg)
So first off thanks for working on this issue and keeping it open I appreciate 1.7.. the only bummer part is I still can't log on I attached a picture trying 15 time to log in. I've tried logging into my friend iphone didnt work to rule out my phone and the android system. Did the password with two step on and got the password set up didn't work.. so can you help me with this issue Wolf, I'm really wanting to get out there and catch the 2nd i've been not able to log in to lol.

**Comment by FernandoTBarros** [comment]
Hey, it's working now?

**Comment by Macgyver7th** [comment]
Ya Niandic throw the rule book at me after I tried to reach out to them on the issue. I never mentioned anything of your program just that I was using something when my phone was over heating for evolves and transfers of Pokemon which was the truth and yes the IV% benefit was nice to lol. It sucks I've been trying to talk them into giving it back since it I hear they issued warnings in the past on more complicated issues. but I've just fallen back into Video Game streaming in the Pokemon absentee months that have pasted. Can't really bring myself to start a new account haha, weird never thought I would have digital bonds with  pokemon hahhah.. anyways thanks for getting back to me brotha, best of luck in the future to you.

**Comment by FernandoTBarros** [comment]
Ok man, sorry to hear that. Good luck on the next!
