### ISSUE TITLE
update to gen 2?

### ISSUE THREAD

**Issue by SlimeKingz** [Wolfsblvt/BlossomsPokemonGoManager#546]
hi,

can you maybe update to gen 2?

**Comment by Cassolotl** [comment]
Not long after gen 2 hit, I got this:

> [00:58:04]: Successfully logged in. Welcome, [username].
> [00:58:04]: Stats: Lvl 25 Valor player.
> [00:58:04]: Pokédex - Types Caught: 132, Total Pokémon Caught: 2238, Total Current Pokémon: 115 (+8 Eggs)
> [00:58:04]: Current version: v0.1.6
> [00:58:04]: Latest version from server: v0.1.6
> [00:58:04]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 23440494375
> [00:58:04]: Highest Gym Offense: Alakazam with Psycho Cut and Psychic has 505862.5
> [00:58:04]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
> [00:58:04]: Load saved locations from file.
> [00:58:05]: java.lang.NullPointerException
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
> [00:58:05]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$14.get(PokeColumn.java:116)
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$1(PokemonTableModel.java:51)
> [00:58:05]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> [00:58:05]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> [00:58:05]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> [00:58:05]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> [00:58:05]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> [00:58:05]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> [00:58:05]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> [00:58:05]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> [00:58:05]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:46)
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
> [00:58:05]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1045)
> [00:58:05]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:249)
> [00:58:05]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
> [00:58:05]: 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> [00:58:05]: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> [00:58:05]: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> [00:58:05]: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> [00:58:05]: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> [00:58:05]: 	at java.security.AccessController.doPrivileged(Native Method)
> [00:58:05]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> [00:58:05]: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> [00:58:05]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> [00:58:05]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> [00:58:05]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> [00:58:05]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> [00:58:05]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> [00:58:05]: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

The weird thing was, it was working for around a day after the first gen 2 pokémon showed up. It wasn't showing any gen 2 pokémon, but it was still good for gen 1. And then it refused to reload, so I restarted, and blammo. Empty. :(

**Comment by schagnon** [comment]
It's silly the number of people who will submit the same issue over and over again.   People this is a known issue.

**Comment by nhahtdh** [comment]
Well, the API still works. The stack trace shows that it's due to a new move not in the database.

**Comment by kribjo** [comment]
Thanks nhahtdh for the by far most constructive comment in the comment sections of these three recent issue reports!

**Comment by Cassolotl** [comment]
@schagnon If you're gonna take the time to criticise someone reporting a known bug, also maybe take the time to include a URL to the correct thread thing, please!

Edit: I am not very techy, so I don't know how to recognise some of the known bugs from title alone. I just picked the first title that looked like it might be related to the issue and commented there. Discouraging people from reporting bugs just means less bug reports and people feeling bad.

**Comment by Wolfsblvt** [comment]
Everything fine, we are all friendly around here. Right? (:
We want to support each other and make our Pokémon Go experience better!

Duplicate issues can be prevented, but aren't that bad. I just close them and everything goes on as normal. Then it's up to OP and the other ones with the issue to follow up on the original issue, which GitHub makes kind of easy.

The first issue about this topic is #541. That's at least the one I am sticking to now.

The reason why it doesn't work is not the new API, but what @nhahtdh explained correctly:
> Well, the API still works. The stack trace shows that it's due to a new move not in the database.

**Comment by Cassolotl** [comment]
@Wolfsblvt Thank you! :)
