### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [Wolfsblvt/BlossomsPokemonGoManager#549]
I've been checking several times a day since gen 2 was released. Apart from some activity in Issues, nothing seems to happen anymore. It's a great tool, should I start learning Java to resurrect it?

Jo

**Comment by Cirunz** [comment]
There's activity here #541  just about the second gen. The author answered and is working on it, but I think this change of API is sorta big of a problem to address, so it take some time.
I work with others API myself and I can tell you a sudden change like that can make your life miserable for much more than three days, even when is your day job, and not something you do in your spare time :)

**Comment by Wolfsblvt** [comment]
@FernandoTBarros Has made most of the stuff concerning Gen 2, on his fork of course, the PR is the one linked (:
Will be merged soon and then released.

So no, nothing dead :P

**Comment by PolyglotOpenstreetmap** [comment]
Big thank you and I apologize for having been somewhat impatient.

**Comment by Wolfsblvt** [comment]
No worries. I understand it. Was difficult for me too, constantly at the 1000 Pokémon limit, and I had to transfer blind xD
