### ISSUE TITLE
Search function truncation and "total highlighted"

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#56]
Hi! Awesome work, wanted to leave a few bugs:
1. Typing in "Pidgey" brings up Pidgey and Pidgeotto. Seems search is only taking the value up to "e" for some reason.
2. When we highlight within the inapp cells, it'd be cool like in Excel / Word / Folder structures where we see at the bottom of a window, the status bar indicating how many are currently highlighted. This might be a dupe of another defect/enhancement where we're asking how many total Evolve's we've selected, etc.

**Comment by ISeeTanamon** [comment]
Oh. I imagine its not truncating, but maybe theres a field thats indicating a previous evolution. I type in Ekans and Arbok shows up, probably some hidden field showing that Ekans is needed for the Arbok? /2cents.

**Comment by Wolfsblvt** [comment]
First one is cause you can also search for pokémon family. And Pidgey and Pigeottos family is _Pidgey_ (:

Second is a good idea. We should add highlight count maybe when we rework selecting like in #24 suggested.

**Comment by phronx** [comment]
Would it be possible to add the option to enable and disable search for pokémon family?

**Comment by Wolfsblvt** [comment]
Okay, show how much are selected will be added with #24 I would say.  
For the second thing I have opened a new issue #62.

Will close this now here then.
