### ISSUE TITLE
Add collaborator names in Help window

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#57]
Heya guys. @Blossomforth said that he wanted to add us as collaborators in the "Help" window and such.
Would just do that, but I guess it would be fair to ask everyone if he wants to be named there, and what name exactly should be written there. Some want GitHub usenames, others real names, etc.

Pinging @wullxz , @Ljaysoft , @weblue and @Wolfsblvt .

**Comment by Wolfsblvt** [comment]
I'll start then. Please, just add **Wolfsblvt**. My nick is know well enough and don't want my real name placed over the web.

**Comment by Ljaysoft** [comment]
Keep Ljay for me

**Comment by ghost** [comment]
Of course, if you do not wish to be included, that is perfectly fine as well!

**Comment by weblue** [comment]
Let's put this down as a last thing to add before the next major release

**Comment by ghost** [comment]
Agreed.

**Comment by Wolfsblvt** [comment]
Yeah, not that important, but it doesn't hurt if the collaborators already mention how they want to be mentioned in that section. In that case it doesn't matter who does this short PR, it just works.
