### ISSUE TITLE
Columns for Gym Defense/Offense/Duel Ability

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#60]
"Add data related to Gym Defense/Offense/Duel Ability from https://docs.google.com/spreadsheets/d/1hcFo7-UGWx1k1u1BHOvDhq8foPeRr7YbX2jLjjJK0Qw/edit#gid=1036598933 to help with Ranking."

Original idea split from #42. Pinging @psentenac.

**Comment by Wolfsblvt** [comment]
I am not really sure if we should add that. Sounds like very complicated calculations, with data we already display. What do you think, @Blossomforth?

**Comment by xephael** [comment]
Just to add my 2 cents, I think this would be very useful, I might be able to help with the calculations if you want to point me to where in the code they'd need to be done.

**Comment by ghost** [comment]
Wait, gyms? I've never really played against gyms,. so i'm not sure. How could this possibly be useful for an application that doesnt even set the location of the player when logging in?  Or are these stats from the pokemon species themselves?

**Comment by weblue** [comment]
Its based on IVs and the moves the Pokémon has access to

**Comment by xephael** [comment]
@Blossomforth It's just the stats for how good a Pokemon would be in a gym calculated by the moves and IVs of the pokemon.

Edit: @weblue Beat me to it lol

**Comment by Wolfsblvt** [comment]
Guess we can add that then. Columns will be hideable soon.

**Comment by 607ch00** [comment]
Would really love this feature especially with the upcoming batch renaming. My current manual format is something like (please excuse my PHP):

``` php
<?php

if ($attackMove ==1 && $defenseMove == 1) {
    $moveTag = 'PP';
} elseif ($attackMove < .9 && $defenseMove < .9) {
    $moveTag = 'X';
} else {
    if ($attackMove == 1) {
        $attackTag = 'AP';
    } elseif ($attackMove > .9) {
        $attackTag = 'A';
    }

    if ($defenseMove == 1) {
        $defenseTag = 'DP';
    } elseif ($defenseMove > .9) {
        $defenseTag = 'D';
    }

    if ($attackMove >= $defenseMove) {
        $moveTag = $attackMove.$defenseMove;
    } else {
        $moveTag = $defenseMove.$attackMove;
    }

}

$maxNameLength = 12;

if ($pokeIV < 90%) {
    $monTags = $ivPercentage.$moveTag;
} else {
    $monTags = $ivAttack.'/'.$ivDefense.'/'.$ivStamina.$moveTag;
}

$shortMonName = substr(0, ($maxNameLength-strlen($monTags)));
$monName = $shortMonName.$monTags;
```

**Comment by Jbz797** [comment]
What do you think about this doc?

https://docs.google.com/spreadsheets/d/1bZWRNBEjYlKyrkzNV6-wQ1RLq6qj_V54oYkvnKyEMsk/edit?usp=sharing

It would be possible to add two columns -> " Moves % " and " Global % "
- " Moves % " only for pokemons in their last evolution
- " Global % "  would be an average between IV % and Moves %

**Comment by Wolfsblvt** [comment]
That's a lot of stuff and bif formulas in the background. We will think about adding that. But will be much later though.

**Comment by Jbz797** [comment]
I'm a front-end developer and unfortunately I don't know java otherwise I have helped you.

**Comment by Wolfsblvt** [comment]
What you could do is extract those complicated formulas in some kind of human-readable stuff, pseudo-code with explanations and so on.

That would help us developers to implement these functions much faster.

**Comment by patrissimo** [comment]
Relatedly; I've noticed your DPS data for moves sometimes differs from various websites. Not sure how you are deriving it, but might want to double-check the formula.

You could also just make it a config file based on data export from a spreadsheet like the one linked, then the user can tweak values in the rare case that they want to, and you don't have to do the calcs/understand the formula. You can specialize in collection management rather than move analytics.

**Comment by Jbz797** [comment]
@patrissimo My " % Move " sometimes differs because, contrast to the others I considers the defensives capabilities (Gym Def). For the DPS i will check that.

@Wolfsblvt I will collect the datas and do the calculations in javascript with comments.

**Comment by Wolfsblvt** [comment]
I guess this issue is resolved with one of the latest PRs?
This here: #213 

Agreed, @607ch00, @QuadTog and the others here? Then I'll close.
