### ISSUE TITLE
Sort by multiple columns

### ISSUE THREAD

**Issue by zeeshan-m** [Wolfsblvt/BlossomsPokemonGoManager#7]
Allow sorting by multiple columns, i.e. when choosing what to evolve or discard sorting by species, CP and IV would be very helpful

**Comment by JaymerJaymer** [comment]
It already does this !!!

A trick for sorting that has existed for years is:
Pick your 3 columns you want to sort by, then sort them in reverse order - try it...
click on these columns:

CP
Move 2
Type 1

As it does the "next" sort, it keeps the sort order from the previous sort.

This gives you your Dex sort by
Type 1, and within that by Move 2 and CP inside that.

**Comment by wullxz** [comment]
See #13

**Comment by ghost** [comment]
Thanks for the suggestion :) As JaymerJaymer found that they do work that way already, I'm going to go ahead and close this issue. Feel free to comment if you have any other input :)
