### ISSUE TITLE
Settings for which columns should be displayed

### ISSUE THREAD

**Issue by OSwoboda** [Wolfsblvt/BlossomsPokemonGoManager#70]
I've noticed that many more columns are added and some of them are useful for my use cases and others not. That's why it needs to be possible to configure which columns should be displayed and which not. But I guess therefore we need to wait for https://github.com/Blossomforth/BlossomsPokemonGoManager/issues/61.

**Comment by Wolfsblvt** [comment]
It's already noted as "hiding" in #65. Guess that's what you mean?
We will work on that soon (:

Will close that here then, as duplicate. If it's not the same, just write what you mean different.
