### ISSUE TITLE
[Suggestion] Rename ability?

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#71]
Hi!

Wondering if theres a renaming ability / if its feasible from this Java UI? Makes marking pokemon with particular IV's / ready to evolve much easier than comparing what you want in the Java UI and then changing ingame.

Tried searching for issues with "rename" and didn't get anything. Thanks!

**Comment by Ljaysoft** [comment]
Similar to #47 but more specific I guess. Will need a UI change for that.

**Comment by Wolfsblvt** [comment]
Why is that different to 47?
You can just select one with the bulk feature and don't use placeholders, just text, in that case you have what was requested here.
Or do I understand something wrong?

**Comment by Ljaysoft** [comment]
Ah ok nvm, I actually didn't really check the details of the placeholders feature. What is asked is to change the name directly in the field of the list, not sure how the bulk rename feature would be implemented, that's why

**Comment by Wolfsblvt** [comment]
Bulk rename would be a button where you can select multiple rows and click, or just a single row and click, I guess.  
So it was meant inline-edit if you click on the name cell?

I am still not sure if this issue isn't just a duplicate or the rename feature.

**Comment by Ljaysoft** [comment]
yeah, inline editing

**Comment by Wolfsblvt** [comment]
Shall we add that to the bulk renaming feature and just do that with one step?
I guess the inline editing is just a bit of UI code, it can use the exact same bulk renaming function.

**Comment by Wolfsblvt** [comment]
Continue that one in #47 now.
