### ISSUE TITLE
Evolving without enough candy message

### ISSUE THREAD

**Issue by eralpsahin** [Wolfsblvt/BlossomsPokemonGoManager#76]
Trying to Evolve without enough candy gives this not user friendly message

> [08/06 22:53:07]: Error evolving Com.pokegoapi.api.map.pokemon.evolutionresult @ 377ded3b, result: com.pokegoapi.api.map.pokemon.EvolutionResult @ 6bf9d479

**Comment by weblue** [comment]
On it
