### ISSUE TITLE
What data should we be defining in the Pokemon Table?

### ISSUE THREAD

**Issue by ghost** [Wolfsblvt/BlossomsPokemonGoManager#77]
So, the data we're implementing into the pokemon table is getting pretty ridiculous. Lots of information that may be useful for sorting pokemon or for comparing pokemon, but not for both, and even some for neither.

So, what data should we implement in the table itself, and what data should we be extracting out of the table, into an individual pokemon stats window?

**Comment by Wolfsblvt** [comment]
I (for myself) would want to have the option for ALL columns. Maybe I need some now, some while doing candy evolve, etc.

If we give the user the ability to hide columns, reorder them, and if we have lots of columns hidden by default, is there any reason to not have them as column option _if the user wants that_?
Sure, a Pokémon info window would be cool, but having those stats as columns if you want them too.

**Comment by Scott7789** [comment]
I second @Wolfsblvt. I'd love to be able to control which columns I see.

**Comment by ghost** [comment]
I agree then, as well. :)
