### ISSUE TITLE
UI is starting to be confusing.

### ISSUE THREAD

**Issue by eralpsahin** [Wolfsblvt/BlossomsPokemonGoManager#83]
![ivtextboxrightinthemiddle](https://cloud.githubusercontent.com/assets/10602289/17463786/8cd7c15a-5cd6-11e6-8c81-4714e7e9ed68.png)
1. I think settings like **transfer after evolution should not be in Menu Bar**, we can create settings tabs for them, or maybe with new UI there may be space for all the operations.
2. **Pokemon IV textbox size is so small** in the default size now. The white thing between select pokemon IV and power up selected

**Comment by Wolfsblvt** [comment]
Settings window is planned with #61 already, hope that does a lot of things that can be seperated.
Guess we should really work on the UI. But some of us already do, so wait for the first changes.

For me, I think we should separate options that work on the table (refresh, select less than IV, and stuff), and all those bulk operations. All in one line is confusing. Seperating them and making it visible what you do would help a lot, I guess.

But yeah, let's keep that open here as the general UI overhaul issue. There needs to be done a lot.

**Comment by Ljaysoft** [comment]
I'm currently building a totally revampedG UI with JavaFX.
Windows are configured in fxml files, with a controller for each View.
The way to implement the GUI is similar to android projects(the other similar thing I know).
I'll have a mockup ready soon.
