### ISSUE TITLE
"Natural" delays on bulk operations

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#84]
To don't get flagged as a bot that fast and to make the tool more _believable_, we want to add configurable delays between each bulk operation, so that users can decide how long they want to wait between each individual step of a bulk operation.

There should be a min and a max time and the wait time chosen between each step should be random, to make it less generic and computer-generated.

**Comment by Lacero** [comment]
I agree completely. If Niantic comes down on automated gameplay, the calls to transfer and evolve may not be distinguishable from the bots.

Don't make the wait time be whole or fractional seconds. Needs to be a random float or double in ms. Probably need an outlier once every X actions that takes much longer than the normal range so as to simulate a player getting distracted or pausing to think.
