### ISSUE TITLE
Cannot transfer multiple times in one session.

### ISSUE THREAD

**Issue by Benny-Git** [Wolfsblvt/BlossomsPokemonGoManager#9]
Looks like the ActionListener is only good for one transfer, but the button doesn't react again when I want to initiate another transfer.

**Comment by ghost** [comment]
Whoopsies, i forgot to close this. This was fixed in the most recent commit :) I'll be packaging it together with a 0.1.1 release later on tonight!

**Comment by Scott7789** [comment]
Do you have any estimation on when 0.1.1 will be released? Love your product. Thanks for all your hard work.
