### ISSUE TITLE
Changing account

### ISSUE THREAD

**Issue by Doshunn** [Wolfsblvt/BlossomsPokemonGoManager#94]
Hi I've logged in with the wrong google account and want to know how to switch to the right one. Tried logging out then back in but it seems to always log me back in using the initially used(wrong) account. How to I fully log out to log back in with the right account ?

Thanks ever so much for this handy tool !!

**Comment by Doshunn** [comment]
Ok found the config.json file: 

{
    "options": {"lang": "en"},
    "login": {
        "GoogleAuthToken": "",
        "SaveAuth": true
    }
}

I removed the Token and now want it to prompt me to allow access again on the website so that it generates a new token. But does not work anymore. I just get "Unfortunately your login has failed, press ok to try again"

So how do I prompt it to re-generate that page and create a new token ?

**Comment by Wolfsblvt** [comment]
Try deleting the whole entry in that `config.json` file for that Auth: `"GoogleAuthToken": "",`. Otherwise, delete the whole config file. There isn't much in it for you anyways right now.

But you are right, we need to rework logging in feature for saved accounts.

**Comment by Doshunn** [comment]
Nice one bud, deleted the file itself and it's working now. It re-opened the webpage and generated a new token. Thanks for your help ! :)
