### ISSUE TITLE
[suggestion] ability to enter a nickname

### ISSUE THREAD

**Issue by cbartholomew** [Wolfsblvt/BlossomsPokemonGoManager#96]
my so loves the tool, but she's obsessed with giving them nicknames, anyway the new ui could contain the ability to apply a nickname to the pokemon? 

thanks.

**Comment by Wolfsblvt** [comment]
Yep, already a suggestion open for renaming: #47
Which can do small nickname renaming, but even much more! Pull request is on its way and it will be released in the next version (:
